# Generated by Django 5.2.6 on 2025-10-24 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_alter_order_options_alter_orderitem_price_at_moment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="Описание"
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=False,
                        help_text="Неактивные опции скрыты из карточки товара.",
                        verbose_name="Активна",
                    ),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="store.product",
                        verbose_name="Товар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Опция товара",
                "verbose_name_plural": "Опции товара",
                "ordering": ["sort_order", "id"],
                "unique_together": {("product", "name")},
            },
        ),
        migrations.AddField(
            model_name="orderitem",
            name="option",
            field=models.ForeignKey(
                blank=True,
                help_text="Опция, выбранная покупателем.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="store.productoption",
            ),
        ),
    ]
