# Generated by Django 5.2.6 on 2025-10-24 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0005_productoption_orderitem_option"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["name"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="productoption",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "Product option",
                "verbose_name_plural": "Product options",
            },
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Upload a 16:9 category cover",
                null=True,
                upload_to="store/categories/",
                verbose_name="Image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=120, unique=True, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(unique=True, verbose_name="Slug"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="option",
            field=models.ForeignKey(
                blank=True,
                help_text="Option chosen by the customer.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to="store.productoption",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="description",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="is_active",
            field=models.BooleanField(
                default=False,
                help_text="Inactive options are hidden on the product page.",
                verbose_name="Active",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="name",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="options",
                to="store.product",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="sort_order",
            field=models.PositiveIntegerField(default=0, verbose_name="Sort order"),
        ),
    ]
