# Generated by Django 5.2.6 on 2025-10-24 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0006_alter_category_options_alter_productoption_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave empty to inherit the product price.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price override",
            ),
        ),
    ]
