# Generated by Django 5.2.6 on 2025-10-25 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0007_productoption_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="compatibility",
            field=models.TextField(
                blank=True,
                help_text="Free-form compatibility notes shown on the product page.",
            ),
        ),
    ]
