# Generated by Django 5.2.6 on 2025-10-25 01:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0008_product_compatibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="contact_for_estimate",
            field=models.BooleanField(
                default=False,
                help_text="Show “Contact for estimate” instead of the numeric price on the storefront.",
                verbose_name="Contact for estimate",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="estimate_from_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional hint that displays as “From $X”.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Starting from",
            ),
        ),
    ]
