# Generated by Django 5.2.6 on 2025-10-25 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0009_product_contact_for_estimate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional photo reference uploaded at checkout.",
                null=True,
                upload_to="store/order_attachments/",
            ),
        ),
    ]
