# Generated by Django 5.2.6 on 2025-10-25 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0010_order_reference_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFitmentRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot of the product name so context is not lost if the product is removed.",
                        max_length=180,
                    ),
                ),
                (
                    "customer_name",
                    models.CharField(max_length=140, verbose_name="Customer name"),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=40)),
                (
                    "vehicle",
                    models.CharField(
                        blank=True,
                        help_text="Chassis, platform, or vehicle description shared by the customer.",
                        max_length=180,
                    ),
                ),
                (
                    "performance_goals",
                    models.CharField(
                        blank=True,
                        help_text="Power goals or intended usage spelled out by the customer.",
                        max_length=200,
                    ),
                ),
                (
                    "timeline",
                    models.CharField(
                        blank=True,
                        help_text="Requested timing or deadline for the build.",
                        max_length=140,
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True,
                        help_text="Free-form notes provided by the customer.",
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Where on the site the request originated.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("in_progress", "In progress"),
                            ("responded", "Responded"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Product the request originated from (if it still exists).",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fitment_requests",
                        to="store.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Custom fitment request",
                "verbose_name_plural": "Custom fitment requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
