# Generated by Django 5.2.6 on 2025-11-10 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0011_customfitmentrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="customfitmentrequest",
            name="budget",
            field=models.CharField(
                blank=True,
                help_text="Budget or target spend shared by the customer.",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="customfitmentrequest",
            name="submodel",
            field=models.CharField(
                blank=True,
                help_text="Trim or submodel details provided by the customer.",
                max_length=140,
            ),
        ),
    ]
