# Generated by Django 5.2.6 on 2025-11-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0012_customfitmentrequest_budget_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="CAD", max_length=3),
        ),
    ]
