# Generated by Django 5.2.6 on 2025-12-09 22:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0013_alter_product_currency"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_balance_due",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_card_brand",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_fee",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_last4",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_mode",
            field=models.CharField(
                choices=[("full", "Pay in full"), ("deposit_50", "50% deposit")],
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_processor",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_receipt_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("unpaid", "Unpaid"), ("paid", "Paid"), ("failed", "Failed")],
                db_index=True,
                default="unpaid",
                max_length=20,
            ),
        ),
    ]
