# Generated by Django 4.2.11 on 2026-01-14 03:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0017_cleanup_batch"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePricingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_multiplier_percent",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Applies to all store product and option prices. 100 = no change, 110 = +10%. Use whole percents.",
                        verbose_name="Price multiplier (%)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store pricing settings",
                "verbose_name_plural": "Store pricing settings",
            },
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Base price before the global multiplier.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Leave empty to inherit the product price. Global multiplier still applies.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price override",
            ),
        ),
    ]
