# Generated by Django 4.2.11 on 2026-01-14 04:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0020_order_review_request_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_in_house",
            field=models.BooleanField(
                default=False,
                help_text="Exclude this product from the global price multiplier.",
                verbose_name="In-house product",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text=(
                    "Leave empty to inherit the product price. "
                    "Global multiplier still applies unless the product is in-house."
                ),
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Price override",
            ),
        ),
        migrations.AlterField(
            model_name="storepricingsettings",
            name="price_multiplier_percent",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text=(
                    "Applies to all store product and option prices "
                    "except in-house products. 100 = no change, 110 = +10%. "
                    "Use whole percents."
                ),
                verbose_name="Price multiplier (%)",
            ),
        ),
    ]
