# Generated by Django 4.2.11 on 2026-01-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0021_product_in_house"),
    ]

    operations = [
        migrations.AddField(
            model_name="productoption",
            name="is_separator",
            field=models.BooleanField(
                default=False,
                help_text="Show this option as a non-selectable separator in the option list.",
                verbose_name="Separator",
            ),
        ),
    ]
