# Generated by Django 5.2.4 on 2026-02-05 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0022_productoption_separator"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="option_column_1_label",
            field=models.CharField(
                blank=True,
                help_text="Heading shown above the first option column on the product page.",
                max_length=60,
                verbose_name="Option column 1 label",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="option_column_2_label",
            field=models.CharField(
                blank=True,
                help_text="Heading shown above the second option column on the product page.",
                max_length=60,
                verbose_name="Option column 2 label",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="option_column",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Column 1"), (2, "Column 2")],
                default=1,
                help_text="Which option column to show this option under on the product page.",
                verbose_name="Display column",
            ),
        ),
    ]
