# Generated by Django 5.2.4 on 2026-02-07 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0023_product_option_column_1_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="main_image",
            field=models.ImageField(
                blank=True, max_length=2048, null=True, upload_to="store/products/"
            ),
        ),
    ]
