# Generated by Django 5.2.4 on 2026-02-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0024_alter_product_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="reference_image",
            field=models.ImageField(
                blank=True,
                help_text="Optional reference image for logos, artwork, inspiration, or fitment examples uploaded at checkout.",
                null=True,
                upload_to="store/order_attachments/",
            ),
        ),
    ]
