# Generated by Django 5.2.4 on 2026-02-12 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0025_alter_order_reference_image_help_text"),
        ("store", "0025_customfitmentrequest_reference_image"),
    ]

    operations = []
