# Generated by Django 5.2.4 on 2026-02-14 03:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0027_store_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoreShippingSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_threshold_cad",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Orders shipping to Canada at or above this subtotal are eligible for free shipping. Leave blank (or set to 0) to disable.",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Free shipping threshold (Canada, CAD)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store shipping settings",
                "verbose_name_plural": "Store shipping settings",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="unit_cost",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional internal cost used for margin reporting (not shown to customers).",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Cost / value (per unit)",
            ),
        ),
    ]
