# Generated by Django 5.2.4 on 2026-02-14 04:46

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0028_storeshippingsettings_product_unit_cost"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Delivery cost applied at checkout (before GST/fees).",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Shipping / delivery cost",
            ),
        ),
        migrations.AddField(
            model_name="storeshippingsettings",
            name="delivery_cost_under_threshold_cad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Charged at checkout when shipping merch to Canada and the cart subtotal is below the free shipping threshold. Leave blank (or set to 0) to disable.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Delivery cost under free-shipping threshold (Canada, CAD)",
            ),
        ),
    ]
