# Generated by Django 5.2.4 on 2026-02-14 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0029_order_shipping_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=120, unique=True, verbose_name="Name"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=140, unique=True, verbose_name="Slug"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True,
                        help_text="Optional override. When empty, the first product image is used.",
                        max_length=2048,
                        null=True,
                        upload_to="merch/categories/",
                        verbose_name="Cover image",
                    ),
                ),
                (
                    "cover_image_alt",
                    models.CharField(
                        blank=True, max_length=140, verbose_name="Cover alt text"
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Merch category",
                "verbose_name_plural": "Merch categories",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="merch_category",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional merch category for the /merch landing page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="store.merchcategory",
            ),
        ),
    ]
