# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0031_orderpromocode_productdiscount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_numbers",
            field=models.TextField(
                blank=True,
                default="",
                help_text="One per line. Shown in the client portal after shipping.",
                verbose_name="Tracking numbers",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Optional carrier tracking URL shown in the client portal.",
                verbose_name="Tracking link",
            ),
        ),
    ]

