# Generated by Django 5.2.4 on 2026-03-05 22:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0032_order_tracking_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="printful_error",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Last fulfillment error returned by Printful, if any.",
                verbose_name="Printful error",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_external_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Idempotent external order ID used when creating Printful orders.",
                max_length=140,
                verbose_name="Printful external ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_last_synced_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this order was last updated from Printful.",
                null=True,
                verbose_name="Printful last synced at",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_order_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Connected Printful order ID after merch fulfillment submission.",
                null=True,
                verbose_name="Printful order ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_shipping_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Shipping amount returned by Printful for the selected rate.",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Printful shipping cost",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_shipping_currency",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Currency code returned by Printful shipping/order APIs.",
                max_length=8,
                verbose_name="Printful shipping currency",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_shipping_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Customer-facing Printful shipping method label used at checkout.",
                max_length=140,
                verbose_name="Printful shipping method",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_shipping_rate_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Chosen Printful shipping rate identifier from checkout.",
                max_length=80,
                verbose_name="Printful shipping rate ID",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_status",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Last known Printful order status from API/webhooks.",
                max_length=40,
                verbose_name="Printful status",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_submitted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When this order was first submitted to Printful.",
                null=True,
                verbose_name="Printful submitted at",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="printful_tracking_data",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Normalized tracking entries received from Printful webhooks.",
                verbose_name="Printful tracking payload",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="printful_external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional external identifier mirrored from Printful.",
                max_length=140,
                verbose_name="Printful external ID",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="printful_product_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Connected Printful sync product ID for merch items.",
                null=True,
                verbose_name="Printful product ID",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="printful_external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional external variant identifier mirrored from Printful.",
                max_length=140,
                verbose_name="Printful external ID",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="printful_sync_variant_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Connected Printful sync variant ID for merch fulfillment.",
                null=True,
                verbose_name="Printful sync variant ID",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="printful_variant_id",
            field=models.PositiveIntegerField(
                blank=True,
                db_index=True,
                help_text="Underlying Printful catalog variant ID when available.",
                null=True,
                verbose_name="Printful catalog variant ID",
            ),
        ),
        migrations.CreateModel(
            name="PrintfulWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=80)),
                ("event_hash", models.CharField(max_length=64, unique=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="printful_webhook_events",
                        to="store.order",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_at", "-id"],
            },
        ),
    ]
