# Generated by Django 5.2.4 on 2026-03-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0033_order_printful_error_order_printful_external_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="address_line1",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="address_line2",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="order",
            name="city",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="country",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(blank=True, default="shipping", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="postal_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="order",
            name="region",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
