# Generated by Django 5.2.4 on 2026-03-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0034_order_address_line1_order_address_line2_order_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="printful_product_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="Connected Printful sync product ID for merch items.",
                null=True,
                verbose_name="Printful product ID",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="printful_sync_variant_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="Connected Printful sync variant ID for merch fulfillment.",
                null=True,
                verbose_name="Printful sync variant ID",
            ),
        ),
        migrations.AlterField(
            model_name="productoption",
            name="printful_variant_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="Underlying Printful catalog variant ID when available.",
                null=True,
                verbose_name="Printful catalog variant ID",
            ),
        ),
    ]
