# Generated by Django 5.2.4 on 2026-04-14 21:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0037_product_show_liner_pricing_guide"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="dealer_tier_1_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional fixed dealer price for Tier 1. Used only for in-house products.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tier 1 price",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dealer_tier_2_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional fixed dealer price for Tier 2. Used only for in-house products.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tier 2 price",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="dealer_tier_1_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional fixed Tier 1 dealer price for this option.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tier 1 price",
            ),
        ),
        migrations.AddField(
            model_name="productoption",
            name="dealer_tier_2_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional fixed Tier 2 dealer price for this option.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Tier 2 price",
            ),
        ),
    ]
