# Generated by Django 5.2.4 on 2025-07-14 18:58

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='file',
            field=models.FileField(storage=storages.backends.s3.S3Storage(), upload_to='client_files/'),
        ),
    ]
