# Generated by Django 5.2.4 on 2025-07-13 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='status',
            new_name='payment_status',
        ),
    ]
