# Generated by Django 5.2.4 on 2025-07-21 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_clientfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='source',
            field=models.CharField(default='In-store', max_length=25),
        ),
    ]
