# Generated by Django 5.2.4 on 2025-07-21 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_userprofile_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('reason', models.CharField(choices=[('vacation', 'Vacation'), ('lunch', 'Lunch'), ('break', 'Break')], default='vacation', help_text='Reason for time off', max_length=20)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay')),
            ],
            options={
                'verbose_name': 'Time Off / Vacation',
                'verbose_name_plural': 'Time Offs / Vacations',
            },
        ),
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('work_start', models.TimeField(default='08:00')),
                ('work_end', models.TimeField(default='21:00')),
                ('calendar_color', models.CharField(default='#6bb9f0', help_text='Цвет в календаре (например, #ff99cc)', max_length=7)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to='core.customuserdisplay')),
            ],
        ),
    ]
