# Generated by Django 5.2.4 on 2025-07-21 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_masteravailability_masterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='masterprofile',
            name='calendar_color',
        ),
    ]
