# Generated by Django 5.2.4 on 2025-07-12 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_appointment_master'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='master',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='master_service',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='service_and_master', to='core.servicemaster'),
            preserve_default=False,
        ),
    ]
