# Generated by Django 5.2.4 on 2025-07-12 23:33

import django.contrib.auth.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_remove_appointment_master_remove_appointment_service_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserDisplay',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_client', to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='appointmentstatushistory',
            name='set_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='clientfile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
    ]
