# Generated by Django 5.2.4 on 2025-07-13 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuserdisplay_alter_appointment_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prepaymentoption',
            name='percent',
            field=models.IntegerField(),
        ),
    ]
