# Generated by Django 5.2.4 on 2025-07-30 02:02

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_servicecategory_service_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[core.validators.clean_phone]),
        ),
    ]
