# Generated by Django 5.2.4 on 2025-07-28 04:43

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_clientfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='file',
            field=models.FileField(default='client_files/placeholder.txt', storage=storages.backends.s3.S3Storage(), upload_to='client_files/'),
            preserve_default=False,
        ),
    ]
