# Generated by Django 5.2.4 on 2025-08-02 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_clientsource_alter_userprofile_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='prepayment_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.prepaymentoption'),
        ),
    ]
