# Generated by Django 5.2.4 on 2025-08-05 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_service_prepayment_option'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_master', to='core.masterprofile'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.masterprofile'),
        ),
        migrations.AddField(
            model_name='masterprofile',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.masterroom'),
        ),
    ]
