# Generated by Django 5.2.4 on 2025-08-05 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_masterroom_alter_appointment_master_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_as_master', to='core.customuserdisplay'),
        ),
        migrations.AlterField(
            model_name='servicemaster',
            name='master',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.customuserdisplay'),
        ),
    ]
