# Generated by Django 5.2.4 on 2025-08-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_appointment_master_alter_servicemaster_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★'), (3, '3 ★'), (4, '4 ★'), (5, '5 ★')], help_text='Rating 1 to 5')),
                ('comment', models.TextField(blank=True, help_text='Not obligatory text comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(help_text='One review per one appointment', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.appointment')),
            ],
            options={
                'verbose_name': 'Client Review',
                'verbose_name_plural': 'Client Reviews',
            },
        ),
    ]
