# Generated by Django 5.2.4 on 2025-08-05 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_clientreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percent', models.PositiveIntegerField(help_text='Процент скидки (например, 20 за 20%)')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='core.service')),
            ],
            options={
                'verbose_name': 'Скидка на услугу',
                'verbose_name_plural': 'Скидки на услуги',
                'ordering': ['-start_date'],
            },
        ),
    ]
