# Generated by Django 5.2.4 on 2025-08-05 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_servicediscount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicediscount',
            options={'ordering': ['-start_date'], 'verbose_name': 'Service Discount', 'verbose_name_plural': 'Service Discounts'},
        ),
        migrations.AlterField(
            model_name='servicediscount',
            name='discount_percent',
            field=models.PositiveIntegerField(help_text='Percent of discount'),
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('discount_percent', models.PositiveIntegerField(help_text='discount in percents(0-100)')),
                ('active', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('applicable_services', models.ManyToManyField(blank=True, help_text='leave empty to apply to all services', to='core.service')),
            ],
        ),
        migrations.CreateModel(
            name='AppointmentPromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.appointment')),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.promocode')),
            ],
        ),
    ]
