# Generated by Django 5.2.4 on 2025-08-08 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_servicediscount_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='file_type',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
