# Generated by Django 5.2.4 on 2025-08-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_clientfile_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientfile',
            name='description',
            field=models.CharField(blank=True, help_text="Optional description (e.g., 'Form before procedure')", max_length=255),
        ),
        migrations.AddField(
            model_name='clientfile',
            name='uploaded_by',
            field=models.CharField(choices=[('user', 'Uploaded by user'), ('admin', 'Uploaded by admin')], default='user', help_text='Who uploaded the file: admin or user', max_length=10),
        ),
    ]
