# Generated by Django 5.2.4 on 2025-08-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_clientfile_description_clientfile_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientfile',
            name='uploaded_by',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', help_text='Who uploaded the file: admin or user', max_length=10),
        ),
    ]
