# Generated by Django 5.2.4 on 2025-08-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_userprofile_source_userprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a service cover image (recommended ratio ~16:9).', null=True, upload_to='services/', verbose_name='Image'),
        ),
    ]
