# Generated by Django 5.2.4 on 2025-08-25 18:04

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='masterprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='masters/'),
        ),
    ]
