# Generated by Django 5.2.4 on 2025-08-25 18:15

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_masterprofile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='masters/'),
        ),
    ]
