# Generated by Django 5.2.4 on 2025-08-25 19:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_masterprofile_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dealer_since',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Dealer since'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dealer_tier',
            field=models.CharField(choices=[('NONE', 'None'), ('TIER_5', 'Dealer 5% (≥ $1,000)'), ('TIER_10', 'Dealer 10% (≥ $5,000)'), ('TIER_15', 'Dealer 15% (≥ $20,000)')], default='NONE', max_length=16, verbose_name='Dealer tier'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_dealer',
            field=models.BooleanField(default=False, verbose_name='Is dealer'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DealerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=128, verbose_name='Business name')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('phone', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Phone')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealer_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Reviewed by')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dealer_application', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Dealer Application',
                'verbose_name_plural': 'Dealer Applications',
                'ordering': ['-created_at'],
            },
        ),
    ]
