# Generated by Django 5.2.6 on 2025-10-25 00:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_userprofile_dealer_since_userprofile_dealer_tier_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="masterprofile",
            options={
                "verbose_name": "Staff Profile",
                "verbose_name_plural": "Staff Profiles",
            },
        ),
        migrations.AlterModelOptions(
            name="masterroom",
            options={
                "verbose_name": "Staff Room",
                "verbose_name_plural": "Staff Rooms",
            },
        ),
        migrations.AlterModelOptions(
            name="servicemaster",
            options={
                "verbose_name": "Staff Service Assignment",
                "verbose_name_plural": "Staff Service Assignments",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="contact_for_estimate",
            field=models.BooleanField(
                default=False,
                help_text="Display “Contact for estimate” instead of a fixed price on the storefront.",
                verbose_name="Contact for estimate",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="estimate_from_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Optional “From $X” hint shown next to the contact label.",
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Starting from",
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
