# Generated by Django 5.2.6 on 2025-10-25 01:05

from decimal import Decimal

from django.db import migrations, models


def fill_missing_base_price(apps, schema_editor):
    Service = apps.get_model("core", "Service")
    Service.objects.filter(base_price__isnull=True).update(base_price=Decimal("0.00"))


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_alter_masterprofile_options_alter_masterroom_options_and_more"),
    ]

    operations = [
        migrations.RunPython(fill_missing_base_price, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="service",
            name="base_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
