# Generated by Django 5.2.6 on 2025-10-25 01:51

from django.db import migrations


TERMS_BODY = """
Welcome to Bad Guy Motors. These Terms & Conditions explain how we provide automotive services, sell merchandise, and communicate with you. Please read them carefully before creating an account or booking any service.

1. Scope of Services
We provide custom builds, detailing, maintenance, and parts sales. Availability, pricing, and lead times may change without notice. Any quotes sent via e-mail or chat are valid for 7 calendar days unless stated otherwise.

2. Account Responsibilities
You are responsible for keeping your login credentials confidential. Immediately inform us if you suspect unauthorized use of your account. We may suspend accounts used in violation of local or federal law or our shop policies.

3. Appointments and Cancellations
Appointments require a valid phone number and may require a deposit. Please notify us at least 24 hours in advance for changes or cancellations. Missed appointments or late arrivals may incur shop fees.

4. Payments
We accept major credit cards, ACH transfers, and cash. Unless specifically waived in writing, payments are due immediately when work is completed. Overdue balances may incur a 1.5% monthly finance charge.

5. Vehicle Safety and Warranty
We test every vehicle after service. You agree not to operate the vehicle in an unsafe condition. Any warranty or guarantee will be described on your final invoice. Wear items, racing use, or third-party modifications are excluded from warranty coverage.

6. Updates
We may update these Terms & Conditions to reflect new laws or business processes. The “Last updated” date on the Terms page shows the latest revision. Continued use of your account confirms acceptance of the newest version.

Questions? Contact support@badguymotors.com or visit the shop during business hours.
""".strip()


def seed_terms(apps, schema_editor):
    LegalPage = apps.get_model("core", "LegalPage")
    LegalPage.objects.update_or_create(
        slug="terms-and-conditions",
        defaults={
            "title": "Terms & Conditions",
            "body": TERMS_BODY,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_legalpage"),
    ]

    operations = [
        migrations.RunPython(seed_terms, migrations.RunPython.noop),
    ]
