# Generated by Django 5.2.6 on 2025-10-25 01:57

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_seed_terms_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientfile",
            name="file_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Size in bytes for quick display.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="clientfile",
            name="file",
            field=models.FileField(
                help_text="Uploaded file stored in the configured media storage.",
                storage=django.core.files.storage.FileSystemStorage(),
                upload_to="client_files/",
            ),
        ),
        migrations.AlterField(
            model_name="clientfile",
            name="file_type",
            field=models.CharField(blank=True, editable=False, max_length=50),
        ),
    ]
