# Generated by Django 5.2.6 on 2025-10-25 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0027_clientfile_file_size_alter_clientfile_file_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HeroImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        choices=[
                            ("home", "Home hero"),
                            ("dealer-status", "Dealer banner"),
                            ("store", "Store hero"),
                            ("merch", "Merch hero"),
                        ],
                        max_length=32,
                        unique=True,
                        verbose_name="Placement",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label to help the team identify the asset.",
                        max_length=120,
                        verbose_name="Internal title",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a 16:9 image (webp/jpg recommended, ≤ 2MB).",
                        null=True,
                        upload_to="hero/",
                        verbose_name="Image",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessible description shown to screen readers.",
                        max_length=160,
                        verbose_name="Alt text",
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional short line rendered under the hero image.",
                        max_length=160,
                        verbose_name="Caption / disclaimer",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Hero asset",
                "verbose_name_plural": "Hero assets",
                "ordering": ["location"],
            },
        ),
    ]
