# Generated by Django 5.2.6 on 2025-10-25 03:21

from django.db import migrations, models


def seed_default_tiers(apps, schema_editor):
    DealerTierLevel = apps.get_model("core", "DealerTierLevel")
    defaults = [
        ("NONE", "No discount", 0, 0, 0, "Baseline access"),
        ("TIER_5", "Dealer 5%", 5, 1000, 1, "Earned after $1K lifetime spend"),
        ("TIER_10", "Dealer 10%", 10, 5000, 2, "Unlock at $5K"),
        ("TIER_15", "Dealer 15%", 15, 20000, 3, "Top tier for $20K+"),
    ]
    for code, label, discount, spend, order, description in defaults:
        DealerTierLevel.objects.update_or_create(
            code=code,
            defaults={
                "label": label,
                "discount_percent": discount,
                "minimum_spend": spend,
                "sort_order": order,
                "description": description,
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_hero_images"),
    ]

    operations = [
        migrations.CreateModel(
            name="DealerTierLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("NONE", "None"),
                            ("TIER_5", "Dealer 5% (≥ $1,000)"),
                            ("TIER_10", "Dealer 10% (≥ $5,000)"),
                            ("TIER_15", "Dealer 15% (≥ $20,000)"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
                ("label", models.CharField(max_length=120, verbose_name="Label")),
                (
                    "discount_percent",
                    models.PositiveIntegerField(
                        default=5, verbose_name="Discount percent"
                    ),
                ),
                (
                    "minimum_spend",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Required lifetime spend in USD to qualify for this tier.",
                        verbose_name="Minimum lifetime spend (USD)",
                    ),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Optional helper text shown in the dealer portal.",
                        max_length=200,
                        verbose_name="Short description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dealer tier level",
                "verbose_name_plural": "Dealer tier levels",
                "ordering": ["minimum_spend", "sort_order", "code"],
            },
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="assigned_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Dealer 5% (≥ $1,000)"),
                    ("TIER_10", "Dealer 10% (≥ $5,000)"),
                    ("TIER_15", "Dealer 15% (≥ $20,000)"),
                ],
                help_text="Tier granted by the admin team when approving the account.",
                max_length=16,
                verbose_name="Assigned tier",
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="internal_note",
            field=models.TextField(
                blank=True,
                help_text="Private note for the review team (not shared with the dealer).",
                verbose_name="Internal note",
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="preferred_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Dealer 5% (≥ $1,000)"),
                    ("TIER_10", "Dealer 10% (≥ $5,000)"),
                    ("TIER_15", "Dealer 15% (≥ $20,000)"),
                ],
                default="TIER_5",
                help_text="Requested tier based on projected volume.",
                max_length=16,
                verbose_name="Preferred tier",
            ),
        ),
        migrations.RunPython(seed_default_tiers, migrations.RunPython.noop),
    ]
