# Generated by Django 5.2.6 on 2025-11-10 17:05

import django.db.models.deletion
from django.db import migrations, models


def populate_contact_fields(apps, schema_editor):
    Appointment = apps.get_model("core", "Appointment")
    UserProfile = apps.get_model("core", "UserProfile")

    profile_phones = {
        profile.user_id: profile.phone
        for profile in UserProfile.objects.exclude(phone__isnull=True).exclude(phone__exact="")
    }

    updates = []
    for appt in Appointment.objects.select_related("client"):
        changed = False
        if appt.client_id:
            client = appt.client
        else:
            client = None

        if not appt.contact_name and client:
            full_name = client.get_full_name().strip()
            appt.contact_name = full_name or client.username or client.email
            changed = True

        if not appt.contact_email and client and client.email:
            appt.contact_email = client.email
            changed = True

        if not appt.contact_phone:
            if client and client.id in profile_phones:
                appt.contact_phone = profile_phones[client.id]
                changed = True

        if changed:
            appt.save(update_fields=["contact_name", "contact_email", "contact_phone"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0029_dealertierlevel_dealerapplication_assigned_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="appointment",
            name="contact_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="appointment",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="appointment",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments_as_client",
                to="core.customuserdisplay",
            ),
        ),
        migrations.AlterField(
            model_name="appointmentstatushistory",
            name="set_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.customuserdisplay",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="how_heard",
            field=models.CharField(
                blank=True,
                choices=[
                    ("google", "Google search"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                    ("tiktok", "TikTok"),
                    ("friend", "Friends/Family"),
                    ("other", "Other"),
                ],
                max_length=32,
            ),
        ),
        migrations.RunPython(populate_contact_fields, noop),
    ]
