# Generated by Django 5.2.6 on 2025-11-10 17:27

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_appointment_contact_email_appointment_contact_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectJournalEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                (
                    "headline",
                    models.CharField(
                        blank=True,
                        help_text="Optional hero headline override.",
                        max_length=220,
                    ),
                ),
                (
                    "excerpt",
                    models.TextField(
                        blank=True,
                        help_text="Short teaser shown on cards and previews.",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="project-journal/"
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated list (e.g. detailing,vinyl,wrap).",
                        max_length=160,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        help_text="Displayed as 'Client' on the public page.",
                        max_length=120,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="City / facility to boost trust.",
                        max_length=120,
                    ),
                ),
                (
                    "services",
                    models.CharField(
                        blank=True,
                        help_text="Comma separated services rendered.",
                        max_length=200,
                    ),
                ),
                (
                    "result_highlight",
                    models.CharField(
                        blank=True,
                        help_text="Single sentence outcome that appears on cards.",
                        max_length=200,
                    ),
                ),
                (
                    "reading_time",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="Approximate reading time in minutes.",
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("published", "Published")],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project journal entry",
                "verbose_name_plural": "Project journal entries",
                "ordering": ("-published_at", "-created_at"),
            },
        ),
    ]
