# Generated by Django 5.2.6 on 2025-10-27 06:00

from django.db import migrations


TERMS_BODY = """
<p>Bad Guy Motors builds, services, and customizes vehicles with the same care we would use on our own rigs. These Terms &amp; Conditions describe how bookings, payments, and warranty support work inside our shop. Creating an account, booking time, or approving an estimate means you agree to everything below.</p>

<h2>1. Engagement &amp; scheduling</h2>
<ul>
  <li><strong>Quotes &amp; scope.</strong> Estimates list the tasks, parts, and labor hours we are committing to. If the scope changes, we will send a written change order for approval before continuing.</li>
  <li><strong>Deposits.</strong> High-demand fabrication or paint slots may require a non-refundable deposit to hold calendar time. Deposits are applied to the final invoice.</li>
  <li><strong>Rescheduling.</strong> Please give us at least 24 hours’ notice. Missed appointments or repeated late arrivals can incur a shop fee because that lift could have helped another customer.</li>
  <li><strong>Lead-time shifts.</strong> Supply chain issues happen. If parts or materials delay delivery, we will notify you immediately with an updated ETA and options.</li>
</ul>

<h2>2. Estimates, invoices &amp; payments</h2>
<ul>
  <li><strong>Validity.</strong> Written estimates are valid for 7 calendar days unless they state otherwise. After that window, we may need to re-quote pricing or timelines.</li>
  <li><strong>Accepted payment methods.</strong> We take major credit cards, ACH, certified checks, and cash. Balances are due when the vehicle is ready for pickup unless we have a signed payment schedule on file.</li>
  <li><strong>Past-due balances.</strong> Accounts that age beyond 15 days may accrue a 1.5% monthly finance charge and could pause future work until paid.</li>
  <li><strong>Parts ownership.</strong> Custom-ordered parts or branded merchandise become yours once we purchase them on your behalf, even if you postpone the install.</li>
</ul>

<h2>3. Warranty &amp; support</h2>
<p>We want every build to leave the bay dialed and ready. Our warranty policy is straightforward:</p>
<ul>
  <li><strong>Workmanship.</strong> We warranty labor for 12 months from delivery. If something we fabricated or installed fails under normal use, we will repair or replace it at no labor cost.</li>
  <li><strong>Parts.</strong> Manufacturer warranties pass directly to you. We will help coordinate claims, but coverage is ultimately controlled by the part supplier.</li>
  <li><strong>Exclusions.</strong> Competitive racing, abuse, third-party disassembly, or neglect voids warranty support. Wear-and-tear items (pads, fluids, tires, etc.) are also excluded unless stated on your invoice.</li>
  <li><strong>Reporting an issue.</strong> Email support@badguymotors.com with photos, VIN, mileage, and a short description. We will confirm next steps within one business day.</li>
</ul>

<h2>4. Vehicle responsibilities</h2>
<ul>
  <li><strong>Safety.</strong> We test drive or bench-test every vehicle before release. You agree not to operate the vehicle if you suspect a safety issue and will notify us immediately.</li>
  <li><strong>Storage.</strong> Finished vehicles should be picked up within 3 business days of completion to avoid storage fees unless we make other written arrangements.</li>
  <li><strong>Personal items.</strong> Please remove valuables before drop-off. We are not liable for personal gear left in the vehicle.</li>
</ul>

<h2>5. Communication &amp; approvals</h2>
<ul>
  <li><strong>Primary channel.</strong> All approvals live inside the client portal or in a reply to an email sent from @badguymotors.com. This keeps an audit trail for both of us.</li>
  <li><strong>Photos &amp; updates.</strong> We may share progress photos or short clips for transparency. Let us know if you prefer not to have imagery of your vehicle used in marketing materials.</li>
</ul>

<h2>6. Data, privacy &amp; shop media</h2>
<ul>
  <li><strong>Account security.</strong> Keep your login credentials private. Let us know if you suspect unauthorized access and we will reset the account.</li>
  <li><strong>Media rights.</strong> Unless you opt out in writing, you grant Bad Guy Motors permission to photograph or film the vehicle for portfolio, social content, or case studies. We never disclose license plates, VINs, or personal data.</li>
</ul>

<h2>7. Updates to these terms</h2>
<p>We occasionally adjust policies to reflect regulatory changes or new services. The “Last updated” date on this page reflects the most recent version. Continuing to use the portal or approving new work after an update counts as acceptance.</p>

<p>Questions or concerns? Email <a href="mailto:support@badguymotors.com">support@badguymotors.com</a> or call (403) 525-0432. We will always take the time to make things right.</p>
""".strip()


def update_terms(apps, schema_editor):
    LegalPage = apps.get_model("core", "LegalPage")
    LegalPage.objects.update_or_create(
        slug="terms-and-conditions",
        defaults={
            "title": "Terms & Conditions",
            "body": TERMS_BODY,
            "is_active": True,
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_projectjournalentry"),
    ]

    operations = [
        migrations.RunPython(update_terms, migrations.RunPython.noop),
    ]
