# Generated by Django 5.2.6 on 2025-11-10 18:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_update_terms_copy"),
    ]

    operations = [
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("session_key", models.CharField(max_length=64, unique=True)),
                ("user_email_snapshot", models.EmailField(blank=True, max_length=254)),
                ("user_name_snapshot", models.CharField(blank=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("referrer", models.URLField(blank=True, max_length=512)),
                ("landing_path", models.CharField(blank=True, max_length=512)),
                ("landing_query", models.CharField(blank=True, max_length=512)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_sessions",
                        to="core.customuserdisplay",
                    ),
                ),
            ],
            options={
                "ordering": ("-last_seen_at",),
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "page_instance_id",
                    models.CharField(
                        help_text="Client-generated identifier used to keep updates idempotent.",
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("path", models.CharField(max_length=512)),
                ("full_path", models.CharField(blank=True, max_length=768)),
                ("page_title", models.CharField(blank=True, max_length=255)),
                ("referrer", models.CharField(blank=True, max_length=512)),
                ("started_at", models.DateTimeField()),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                (
                    "timezone_offset",
                    models.SmallIntegerField(
                        default=0,
                        help_text="Client timezone offset in minutes (UTC = 0).",
                    ),
                ),
                ("viewport_width", models.PositiveIntegerField(blank=True, null=True)),
                ("viewport_height", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_views",
                        to="core.customuserdisplay",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="page_views",
                        to="core.visitorsession",
                    ),
                ),
            ],
            options={
                "ordering": ("-started_at",),
            },
        ),
    ]
