# Generated by Django 5.2.6 on 2025-11-13 23:45

from django.db import migrations


def ensure_master_roles(apps, schema_editor):
    MasterProfile = apps.get_model("core", "MasterProfile")
    Role = apps.get_model("core", "Role")
    UserRole = apps.get_model("core", "UserRole")

    master_role, _ = Role.objects.get_or_create(name="Master")

    for profile in MasterProfile.objects.select_related("user"):
        user = getattr(profile, "user", None)
        if not user:
            continue
        UserRole.objects.update_or_create(user=user, role=master_role)
        if not user.is_staff:
            user.is_staff = True
            user.save(update_fields=["is_staff"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_visitorsession_pageview"),
    ]

    operations = [
        migrations.RunPython(ensure_master_roles, migrations.RunPython.noop),
    ]
