# Generated by Django 5.2.6 on 2025-11-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_ensure_master_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerapplication",
            name="assigned_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Dealer 5% tier"),
                    ("TIER_10", "Dealer 10% tier"),
                    ("TIER_15", "Dealer 15% tier"),
                ],
                help_text="Tier granted by the admin team when approving the account.",
                max_length=16,
                verbose_name="Assigned tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealerapplication",
            name="preferred_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Dealer 5% tier"),
                    ("TIER_10", "Dealer 10% tier"),
                    ("TIER_15", "Dealer 15% tier"),
                ],
                default="TIER_5",
                help_text="Requested tier based on projected volume.",
                max_length=16,
                verbose_name="Preferred tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealertierlevel",
            name="code",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Dealer 5% tier"),
                    ("TIER_10", "Dealer 10% tier"),
                    ("TIER_15", "Dealer 15% tier"),
                ],
                max_length=16,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="dealertierlevel",
            name="minimum_spend",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Required lifetime spend in CAD to qualify for this tier.",
                verbose_name="Minimum lifetime spend (CAD)",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dealer_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Dealer 5% tier"),
                    ("TIER_10", "Dealer 10% tier"),
                    ("TIER_15", "Dealer 15% tier"),
                ],
                default="NONE",
                max_length=16,
                verbose_name="Dealer tier",
            ),
        ),
    ]
