# Generated by Django 5.2.6 on 2025-11-21 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_alter_dealerapplication_assigned_tier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FontPreset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "font_family",
                    models.CharField(
                        help_text="Primary CSS font-family name (without fallbacks).",
                        max_length=120,
                    ),
                ),
                (
                    "fallback_stack",
                    models.CharField(
                        default='system-ui, -apple-system, "Segoe UI", sans-serif',
                        help_text="Comma-separated fallbacks appended after the primary family.",
                        max_length=255,
                    ),
                ),
                (
                    "static_path",
                    models.CharField(
                        blank=True,
                        help_text="Path inside STATIC files, e.g. fonts/Diesel.ttf.",
                        max_length=255,
                    ),
                ),
                (
                    "font_file",
                    models.FileField(
                        blank=True,
                        help_text="Optional upload when hosting the font via MEDIA.",
                        null=True,
                        upload_to="fonts/",
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        default="font/ttf",
                        help_text="Used for preload links (e.g. font/ttf, font/woff2).",
                        max_length=40,
                    ),
                ),
                (
                    "font_weight",
                    models.CharField(
                        default="100 900",
                        help_text="Value used in @font-face font-weight (e.g. '400' or '100 900').",
                        max_length=40,
                    ),
                ),
                (
                    "font_style",
                    models.CharField(
                        choices=[("normal", "Normal"), ("italic", "Italic")],
                        default="normal",
                        max_length=20,
                    ),
                ),
                (
                    "font_display",
                    models.CharField(
                        default="swap",
                        help_text="font-display value used in @font-face.",
                        max_length=20,
                    ),
                ),
                (
                    "preload",
                    models.BooleanField(
                        default=True,
                        help_text="Preload tag will be emitted when this font is used on a page.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Font preset",
                "verbose_name_plural": "Font presets",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="PageFontSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[("wheel_tire_service", "Wheel & Tire Service page")],
                        help_text="Page that will consume the configured fonts.",
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "body_font",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="body_font_settings",
                        to="core.fontpreset",
                    ),
                ),
                (
                    "heading_font",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="heading_font_settings",
                        to="core.fontpreset",
                    ),
                ),
                (
                    "ui_font",
                    models.ForeignKey(
                        blank=True,
                        help_text="Optional override for navigation, buttons, and labels. Defaults to body font.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ui_font_settings",
                        to="core.fontpreset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page font setting",
                "verbose_name_plural": "Page font settings",
                "ordering": ("page",),
            },
        ),
    ]
