# Generated by Django 5.2.6 on 2025-11-21 22:13

from django.db import migrations


def seed_fonts(apps, schema_editor):
    FontPreset = apps.get_model("core", "FontPreset")
    PageFontSetting = apps.get_model("core", "PageFontSetting")

    font_defaults = [
        {
            "slug": "diesel",
            "name": "Diesel",
            "font_family": "Diesel",
            "static_path": "fonts/Diesel.ttf",
            "mime_type": "font/ttf",
            "font_weight": "100 900",
            "font_style": "normal",
            "font_display": "swap",
            "preload": True,
            "is_active": True,
        },
        {
            "slug": "ford",
            "name": "Ford",
            "font_family": "Ford",
            "static_path": "fonts/Ford.ttf",
            "mime_type": "font/ttf",
            "font_weight": "100 900",
            "font_style": "normal",
            "font_display": "swap",
            "preload": True,
            "is_active": True,
        },
        {
            "slug": "inter",
            "name": "Inter",
            "font_family": "Inter",
            "static_path": "fonts/Inter-Variable.ttf",
            "mime_type": "font/ttf",
            "font_weight": "100 900",
            "font_style": "normal",
            "font_display": "swap",
            "preload": True,
            "fallback_stack": 'system-ui, -apple-system, "Segoe UI", sans-serif',
            "is_active": True,
        },
    ]

    created_fonts = {}
    for payload in font_defaults:
        slug = payload["slug"]
        defaults = {k: v for k, v in payload.items() if k != "slug"}
        font, _ = FontPreset.objects.update_or_create(slug=slug, defaults=defaults)
        created_fonts[slug] = font

    body_font = created_fonts.get("diesel")
    heading_font = created_fonts.get("ford")
    ui_font = created_fonts.get("diesel")  # keep initial UI consistent with body

    if body_font and heading_font:
        PageFontSetting.objects.update_or_create(
            page="wheel_tire_service",
            defaults={
                "body_font": body_font,
                "heading_font": heading_font,
                "ui_font": ui_font,
                "notes": "Initial defaults: body Diesel, headings Ford.",
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0036_fontpreset_pagefontsetting"),
    ]

    operations = [
        migrations.RunPython(seed_fonts, migrations.RunPython.noop),
    ]
