# Generated by Django 5.2.6 on 2025-11-26 01:15

from django.db import migrations, models


def seed_electrical_work_fonts(apps, schema_editor):
    FontPreset = apps.get_model("core", "FontPreset")
    PageFontSetting = apps.get_model("core", "PageFontSetting")

    font_map = {
        font.slug: font
        for font in FontPreset.objects.filter(slug__in=["diesel", "ford"], is_active=True)
    }

    body_font = font_map.get("diesel") or next(iter(font_map.values()), None)
    heading_font = font_map.get("ford") or body_font
    ui_font = body_font

    if not body_font or not heading_font:
        return

    PageFontSetting.objects.update_or_create(
        page="electrical_work",
        defaults={
            "body_font": body_font,
            "heading_font": heading_font,
            "ui_font": ui_font,
            "notes": "Electrical Work landing defaults: body Diesel, headings Ford.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_alter_heroimage_location_alter_pagefontsetting_page"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroimage",
            name="location",
            field=models.CharField(
                choices=[
                    ("home", "Home hero"),
                    ("dealer-status", "Dealer banner"),
                    ("store", "Store hero"),
                    ("merch", "Merch hero"),
                    ("brake-suspension-hero", "Brake & Suspension hero"),
                    ("brake-suspension-gallery-a", "Brake & Suspension gallery — top"),
                    (
                        "brake-suspension-gallery-b",
                        "Brake & Suspension gallery — middle",
                    ),
                    (
                        "brake-suspension-gallery-c",
                        "Brake & Suspension gallery — bottom",
                    ),
                    ("performance-tuning-hero", "Performance Tuning hero"),
                    (
                        "performance-tuning-gallery-a",
                        "Performance Tuning gallery — top",
                    ),
                    (
                        "performance-tuning-gallery-b",
                        "Performance Tuning gallery — middle",
                    ),
                    (
                        "performance-tuning-gallery-c",
                        "Performance Tuning gallery — bottom",
                    ),
                    ("electrical-work-hero", "Electrical Work hero"),
                    ("electrical-work-gallery-a", "Electrical Work gallery — top"),
                    ("electrical-work-gallery-b", "Electrical Work gallery — middle"),
                    ("electrical-work-gallery-c", "Electrical Work gallery — bottom"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Placement",
            ),
        ),
        migrations.AlterField(
            model_name="pagefontsetting",
            name="page",
            field=models.CharField(
                choices=[
                    ("wheel_tire_service", "Wheel & Tire Service page"),
                    ("performance_tuning", "Performance Tuning page"),
                    ("electrical_work", "Electrical Work page"),
                ],
                help_text="Page that will consume the configured fonts.",
                max_length=80,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_electrical_work_fonts, migrations.RunPython.noop),
    ]
