# Generated by Django 5.2.6 on 2025-11-27 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_alter_pagefontsetting_page"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServiceLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("vehicle", models.CharField(blank=True, max_length=160)),
                ("service_needed", models.CharField(max_length=160)),
                ("notes", models.TextField(blank=True)),
                (
                    "source_page",
                    models.CharField(
                        choices=[
                            ("performance_tuning", "Performance tuning"),
                            ("electrical_work", "Electrical work"),
                            ("brake_suspension", "Brake & suspension"),
                            ("wheel_tire_service", "Wheel & tire service"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=64,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Original URL the lead submitted from.",
                        max_length=600,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Service lead",
                "verbose_name_plural": "Service leads",
                "ordering": ("-created_at",),
            },
        ),
    ]
