# Generated by Django 5.2.6 on 2025-11-27 01:40

import django.core.validators
from django.db import migrations, models


def seed_landing_reviews(apps, schema_editor):
    Review = apps.get_model("core", "LandingPageReview")
    samples = [
        {
            "page": "performance_tuning",
            "reviewer_name": "Alex M.",
            "quote": "Bad Guy Motors tuned my truck and the difference is night and day. Smooth power and great communication.",
            "rating": 5,
            "display_order": 1,
        },
        {
            "page": "performance_tuning",
            "reviewer_name": "Jordan S.",
            "quote": "They installed my intake and exhaust properly and helped me plan out the next upgrades. Very professional.",
            "rating": 5,
            "display_order": 2,
        },
        {
            "page": "performance_tuning",
            "reviewer_name": "Tyler R.",
            "quote": "Only shop in Medicine Hat I trust for performance work. Honest and skilled team.",
            "rating": 5,
            "display_order": 3,
        },
        {
            "page": "electrical_work",
            "reviewer_name": "Tj Perry",
            "quote": "Awesome business and people to deal with. They got all the right parts and shipping dealt with. They kept me notified at all times, great shop, I'll be calling back again.",
            "rating": 5,
            "display_order": 1,
        },
        {
            "page": "electrical_work",
            "reviewer_name": "pd88 pd88",
            "quote": "Thanks Kacie at BGM for fixing up my Duramax. Very good work and customer service.",
            "rating": 5,
            "display_order": 2,
        },
        {
            "page": "electrical_work",
            "reviewer_name": "Jake case",
            "quote": "Amazing shop, definitely will be going to Bad Guy Motors again!",
            "rating": 5,
            "display_order": 3,
        },
        {
            "page": "brake_suspension",
            "reviewer_name": "Tj Perry",
            "quote": "Awesome business and people to deal with. They got all the right parts and shipping dealt with. They kept me notified at all times, great shop, I'll be calling back again.",
            "rating": 5,
            "display_order": 1,
        },
        {
            "page": "brake_suspension",
            "reviewer_name": "pd88 pd88",
            "quote": "Thanks Kacie at BGM for fixing up my Duramax. Very good work and customer service.",
            "rating": 5,
            "display_order": 2,
        },
        {
            "page": "brake_suspension",
            "reviewer_name": "Jake case",
            "quote": "Amazing shop, definitely will be going to Bad Guy Motors again!",
            "rating": 5,
            "display_order": 3,
        },
    ]
    for data in samples:
        Review.objects.update_or_create(
            page=data["page"],
            reviewer_name=data["reviewer_name"],
            quote=data["quote"],
            defaults={
                "rating": data["rating"],
                "display_order": data["display_order"],
                "reviewer_title": data.get("reviewer_title", ""),
                "is_published": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_servicelead"),
    ]

    operations = [
        migrations.CreateModel(
            name="LandingPageReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("performance_tuning", "Performance tuning"),
                            ("electrical_work", "Electrical work"),
                            ("brake_suspension", "Brake & suspension"),
                        ],
                        db_index=True,
                        help_text="Landing page that will display this review.",
                        max_length=64,
                    ),
                ),
                ("reviewer_name", models.CharField(max_length=160)),
                (
                    "reviewer_title",
                    models.CharField(
                        blank=True,
                        help_text="Optional label such as vehicle, platform, or role.",
                        max_length=160,
                    ),
                ),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        help_text="Rating between 1 (worst) and 5 (best).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "quote",
                    models.TextField(
                        help_text="Review text that will be shown publicly."
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers appear first on the landing page.",
                    ),
                ),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Landing page review",
                "verbose_name_plural": "Landing page reviews",
                "ordering": ("page", "display_order", "-created_at"),
            },
        ),
        migrations.RunPython(seed_landing_reviews, migrations.RunPython.noop),
    ]
