# Generated by Django 5.2.6 on 2026-01-20 12:00

from django.db import migrations, models


def seed_home_fonts(apps, schema_editor):
    FontPreset = apps.get_model("core", "FontPreset")
    PageFontSetting = apps.get_model("core", "PageFontSetting")

    font_map = {
        font.slug: font
        for font in FontPreset.objects.filter(slug__in=["diesel", "ford"], is_active=True)
    }

    body_font = font_map.get("diesel") or next(iter(font_map.values()), None)
    heading_font = font_map.get("ford") or body_font
    ui_font = body_font

    if not body_font or not heading_font:
        return

    PageFontSetting.objects.update_or_create(
        page="home",
        defaults={
            "body_font": body_font,
            "heading_font": heading_font,
            "ui_font": ui_font,
            "notes": "Home page defaults: body Diesel, headings Ford.",
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0042_landingpagereview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pagefontsetting",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home page"),
                    ("brake_suspension", "Brake & Suspension page"),
                    ("wheel_tire_service", "Wheel & Tire Service page"),
                    ("performance_tuning", "Performance Tuning page"),
                    ("electrical_work", "Electrical Work page"),
                ],
                help_text="Page that will consume the configured fonts.",
                max_length=80,
                unique=True,
            ),
        ),
        migrations.RunPython(seed_home_fonts, migrations.RunPython.noop),
    ]
