# Generated by Django 5.2.6 on 2025-12-09 23:21

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0043_alter_pagefontsetting_page"),
        ("store", "0014_order_payment_amount_order_payment_balance_due_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="balance_due",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Outstanding balance (e.g., when only a deposit was collected).",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_brand",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="payment",
            name="card_last4",
            field=models.CharField(blank=True, default="", max_length=8),
        ),
        migrations.AddField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="CAD", max_length=8),
        ),
        migrations.AddField(
            model_name="payment",
            name="fee_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Processor fee collected for this payment, if available.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked store order, if this payment came from checkout.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="store.order",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="payment_mode",
            field=models.CharField(
                choices=[("full", "Paid in full"), ("deposit_50", "50% deposit")],
                db_index=True,
                default="full",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="processor",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="payment",
            name="processor_payment_id",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="payment",
            name="receipt_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="payment",
            name="appointment",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked appointment, if this payment came from a booking.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.appointment",
            ),
        ),
        migrations.AlterField(
            model_name="servicelead",
            name="source_page",
            field=models.CharField(
                choices=[
                    ("general_request", "General request"),
                    ("performance_tuning", "Performance tuning"),
                    ("electrical_work", "Electrical work"),
                    ("brake_suspension", "Brake & suspension"),
                    ("wheel_tire_service", "Wheel & tire service"),
                    ("other", "Other"),
                ],
                db_index=True,
                default="other",
                max_length=64,
            ),
        ),
    ]
