# Generated by Django 5.2.6 on 2025-12-09 23:21

from decimal import Decimal

from django.conf import settings
from django.db import migrations


def seed_payments(apps, schema_editor):
    Payment = apps.get_model("core", "Payment")
    PaymentMethod = apps.get_model("core", "PaymentMethod")
    Order = apps.get_model("store", "Order")

    currency = getattr(settings, "DEFAULT_CURRENCY_CODE", "CAD")
    method_cache = {}

    paid_orders = Order.objects.filter(payment_status="paid")
    for order in paid_orders:
        if Payment.objects.filter(order_id=order.id).exists():
            continue

        method_name = (order.payment_processor or "Square").strip() or "Square"
        method_name = method_name[:20]
        cache_key = method_name.lower()
        method = method_cache.get(cache_key)
        if method is None:
            method, _ = PaymentMethod.objects.get_or_create(name=method_name.title())
            method_cache[cache_key] = method

        try:
            Payment.objects.create(
                order=order,
                amount=order.payment_amount or Decimal("0.00"),
                currency=currency,
                method=method,
                payment_mode=order.payment_mode or "full",
                balance_due=order.payment_balance_due or Decimal("0.00"),
                processor=order.payment_processor or method_name,
                processor_payment_id=order.payment_id or "",
                receipt_url=order.payment_receipt_url or "",
                card_brand=order.payment_card_brand or "",
                card_last4=order.payment_last4 or "",
                fee_amount=order.payment_fee or Decimal("0.00"),
                created_at=getattr(order, "created_at", None) or None,
            )
        except Exception:
            # best-effort backfill; swallow failures to avoid blocking migration
            continue


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0044_payment_balance_due_payment_card_brand_and_more"),
        ("store", "0014_order_payment_amount_order_payment_balance_due_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_payments, migrations.RunPython.noop),
    ]
