from django.db import migrations, models


def seed_home_copy(apps, schema_editor):
    HomePageCopy = apps.get_model("core", "HomePageCopy")
    HomePageCopy.objects.get_or_create(singleton_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_add_financing_pagefontsetting"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_id", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("skip_to_main_label", models.CharField(default="Skip to main content", max_length=120)),
                ("brand_word_white", models.CharField(default="BAD GUY", max_length=40)),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                ("brand_tagline", models.CharField(default="CUSTOM BUILDS • INSTALLS • UPGRADES", max_length=120)),
                ("nav_toggle_label", models.CharField(default="Toggle navigation", max_length=80)),
                ("nav_services_label", models.CharField(default="Services", max_length=40)),
                ("nav_client_portal_label", models.CharField(default="Client Portal", max_length=60)),
                ("nav_login_label", models.CharField(default="Login", max_length=40)),
                ("nav_products_label", models.CharField(default="Products", max_length=40)),
                ("nav_merch_label", models.CharField(default="Merch", max_length=40)),
                ("nav_merch_badge", models.CharField(default="Soon", max_length=20)),
                ("nav_dealers_label", models.CharField(default="Dealers", max_length=40)),
                ("nav_financing_label", models.CharField(default="Financing", max_length=40)),
                ("nav_about_label", models.CharField(default="About", max_length=40)),
                ("hero_kicker", models.CharField(default="Custom fabrication • Diesel performance", max_length=120)),
                ("hero_title", models.CharField(default="Built to be bad. Engineered to last.", max_length=140)),
                (
                    "hero_lead",
                    models.TextField(
                        default="Bad Guy Motors is Medicine Hat’s premier custom fab and diesel shop. We design and build bumpers, body swaps, lift kits & four-links, and performance upgrades—then finish them with Armadillo or Smooth Criminal Liner. Book a consult and we’ll map your build from concept to keys."
                    ),
                ),
                ("hero_primary_cta_label", models.CharField(default="Explore services", max_length=60)),
                ("hero_secondary_cta_label", models.CharField(default="Booking", max_length=60)),
                ("hero_stat_1_title", models.CharField(default="Alberta-made", max_length=60)),
                ("hero_stat_1_subtitle", models.CharField(default="built in Medicine Hat", max_length=80)),
                ("hero_stat_2_title", models.CharField(default="Custom only", max_length=60)),
                ("hero_stat_2_subtitle", models.CharField(default="no cookie‑cutter kits", max_length=80)),
                ("hero_stat_3_title", models.CharField(default="24/7", max_length=60)),
                ("hero_stat_3_subtitle", models.CharField(default="Book online fast quotes", max_length=80)),
                ("hero_mobile_action_1_title", models.CharField(default="Book a Service", max_length=60)),
                ("hero_mobile_action_1_subtitle", models.CharField(default="Pick date & time", max_length=80)),
                ("hero_mobile_action_2_title", models.CharField(default="Shop Parts", max_length=60)),
                ("hero_mobile_action_2_subtitle", models.CharField(default="In stock & ready", max_length=80)),
                ("hero_mobile_action_3_title", models.CharField(default="Contact Us", max_length=60)),
                ("hero_mobile_action_3_subtitle", models.CharField(default="Call or e‑mail", max_length=80)),
                ("hero_mobile_action_4_title", models.CharField(default="About", max_length=60)),
                ("hero_mobile_action_4_subtitle", models.CharField(default="Who we are", max_length=80)),
                ("services_title", models.CharField(default="What we build", max_length=80)),
                (
                    "services_desc",
                    models.TextField(
                        default="From bolt‑on to one‑off: bumpers, chase racks, headache racks, mudflaps, running boards, lift kits & 4‑links, diesel tuning & hard parts, coatings & liners, body swaps, and more. Browse packages or request a custom quote."
                    ),
                ),
                ("services_cta_label", models.CharField(default="Open services", max_length=60)),
                ("services_mobile_kicker", models.CharField(default="Quick picks", max_length=60)),
                ("services_mobile_action_1_title", models.CharField(default="Fabrication", max_length=60)),
                ("services_mobile_action_1_subtitle", models.CharField(default="Bumpers, racks, swaps", max_length=80)),
                ("services_mobile_action_2_title", models.CharField(default="Suspension", max_length=60)),
                ("services_mobile_action_2_subtitle", models.CharField(default="Lift kits & 4‑links", max_length=80)),
                ("services_mobile_action_3_title", models.CharField(default="Diesel Tuning", max_length=60)),
                ("services_mobile_action_3_subtitle", models.CharField(default="Turbo, injectors, ECU", max_length=80)),
                ("services_mobile_action_4_title", models.CharField(default="Coatings", max_length=60)),
                ("services_mobile_action_4_subtitle", models.CharField(default="Armadillo & liner", max_length=80)),
                ("services_search_placeholder", models.CharField(default="Search a service…", max_length=120)),
                ("services_filter_all_categories_label", models.CharField(default="All categories", max_length=60)),
                ("services_search_button_label", models.CharField(default="Search", max_length=40)),
                ("services_reset_filters_label", models.CharField(default="Reset filters", max_length=60)),
                ("services_live_results_label", models.CharField(default="Search results", max_length=60)),
                ("services_results_label", models.CharField(default="Results", max_length=60)),
                ("services_featured_label", models.CharField(default="Featured services", max_length=80)),
                ("services_no_results_label", models.CharField(default="No results for your query.", max_length=120)),
                ("services_empty_label", models.CharField(default="The catalog will be available soon 👍", max_length=140)),
                ("services_duration_prefix", models.CharField(default="Duration:", max_length=40)),
                ("services_duration_suffix", models.CharField(default="min", max_length=40)),
                ("services_book_now_label", models.CharField(default="Book now", max_length=40)),
                ("services_nothing_found_label", models.CharField(default="Nothing found.", max_length=80)),
                ("services_failed_load_label", models.CharField(default="Failed to load. Please try again.", max_length=120)),
                ("contact_for_estimate_label", models.CharField(default="Contact for estimate", max_length=80)),
                ("from_label", models.CharField(default="From", max_length=40)),
                ("products_title", models.CharField(default="Products", max_length=80)),
                ("products_desc", models.CharField(default="Performance parts curated by BGM. Fresh stock, ready to ship.", max_length=160)),
                ("products_cta_label", models.CharField(default="Open products", max_length=60)),
                ("products_mobile_kicker", models.CharField(default="Quick shop", max_length=60)),
                ("products_mobile_action_1_title", models.CharField(default="Shop Parts", max_length=60)),
                ("products_mobile_action_1_subtitle", models.CharField(default="Fresh stock", max_length=80)),
                ("products_mobile_action_2_title", models.CharField(default="Merch", max_length=60)),
                ("products_mobile_action_2_subtitle", models.CharField(default="Coming soon", max_length=80)),
                ("products_dealer_label", models.CharField(default="Dealer", max_length=40)),
                ("products_save_label", models.CharField(default="Save", max_length=40)),
                ("products_contact_us_label", models.CharField(default="Contact us", max_length=40)),
                ("products_view_label", models.CharField(default="View", max_length=40)),
                ("products_select_options_label", models.CharField(default="Select options", max_length=60)),
                ("products_add_to_cart_label", models.CharField(default="Add to cart", max_length=40)),
                ("products_empty_label", models.CharField(default="No products yet.", max_length=80)),
                ("products_empty_cta_label", models.CharField(default="Explore products", max_length=80)),
                ("how_title", models.CharField(default="How we work", max_length=80)),
                ("how_desc", models.CharField(default="A transparent cycle—from booking to delivery.", max_length=120)),
                ("how_step_1_title", models.CharField(default="Consult & scope", max_length=80)),
                ("how_step_1_desc", models.CharField(default="Tell us your goals, budget, and timeline.", max_length=120)),
                ("how_step_2_title", models.CharField(default="Design & quote", max_length=80)),
                ("how_step_2_desc", models.CharField(default="CAD as needed, milestones, and a written estimate.", max_length=140)),
                ("how_step_3_title", models.CharField(default="Fabricate & update", max_length=80)),
                ("how_step_3_desc", models.CharField(default="Progress pics, approvals, and clear communication.", max_length=140)),
                ("how_step_4_title", models.CharField(default="Delivery & aftercare", max_length=80)),
                ("how_step_4_desc", models.CharField(default="Test drive, torque check, and a care guide.", max_length=140)),
                ("why_title", models.CharField(default="Why choose BGM", max_length=80)),
                ("why_desc", models.CharField(default="We combine aesthetics with engineering discipline.", max_length=140)),
                ("why_tile_1_title", models.CharField(default="No‑compromise materials", max_length=80)),
                ("why_tile_1_desc", models.CharField(default="DOM tubing, proper hardware, and proven parts.", max_length=120)),
                ("why_tile_2_title", models.CharField(default="On‑time, transparent", max_length=80)),
                ("why_tile_2_desc", models.CharField(default="Clear updates, zero guesswork.", max_length=120)),
                ("why_tile_3_title", models.CharField(default="Built for abuse", max_length=80)),
                ("why_tile_3_desc", models.CharField(default="Designed to work hard, not just look pretty.", max_length=120)),
                ("why_warranty_title", models.CharField(default="Warranty & support", max_length=80)),
                ("why_warranty_desc", models.CharField(default="We stand behind our work and make things right.", max_length=120)),
                ("why_warranty_cta", models.CharField(default="Read terms →", max_length=80)),
                ("why_warranty_aria_label", models.CharField(default="Read Terms & Conditions", max_length=120)),
                ("why_warranty_title_attr", models.CharField(default="Warranty & support details", max_length=120)),
                ("faq_title", models.CharField(default="FAQ", max_length=40)),
                ("faq_desc", models.CharField(default="Short and sweet", max_length=80)),
                ("faq_1_question", models.CharField(default="Do I need a prepayment?", max_length=160)),
                (
                    "faq_1_answer",
                    models.CharField(
                        default="For some services — yes (the “prepayment” option in the service card). Others — pay upon completion.",
                        max_length=220,
                    ),
                ),
                ("faq_2_question", models.CharField(default="Can I reschedule?", max_length=160)),
                (
                    "faq_2_answer",
                    models.CharField(
                        default="Yes. In the client portal you can cancel or reschedule, and we’ll auto-suggest free slots.",
                        max_length=220,
                    ),
                ),
                ("faq_3_question", models.CharField(default="Do you work with companies and dealers?", max_length=160)),
                (
                    "faq_3_answer",
                    models.CharField(
                        default="Yes. The “Dealers” section is coming soon. Leave a request via the contact form.",
                        max_length=220,
                    ),
                ),
                ("final_cta_title", models.CharField(default="Ready to upgrade?", max_length=80)),
                ("final_cta_desc", models.CharField(default="We’ll secure your slot and lock the terms today.", max_length=120)),
                ("final_cta_primary_label", models.CharField(default="Explore services", max_length=60)),
                ("final_cta_secondary_auth_label", models.CharField(default="Client Portal", max_length=60)),
                ("final_cta_secondary_guest_label", models.CharField(default="Login", max_length=60)),
                ("contact_fab_label", models.CharField(default="Contact us", max_length=60)),
                ("contact_modal_title", models.CharField(default="Contact us", max_length=60)),
                ("contact_email_label", models.CharField(default="E-mail", max_length=40)),
                ("contact_phone_label", models.CharField(default="Phone", max_length=40)),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                ("contact_copy_success_label", models.CharField(default="Copied", max_length=40)),
                ("contact_copy_failed_label", models.CharField(default="Copy failed", max_length=40)),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                ("contact_write_email_label", models.CharField(default="Write e-mail", max_length=60)),
                ("contact_text_label", models.CharField(default="Text us", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Home page copy",
                "verbose_name_plural": "Home page copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.RunPython(seed_home_copy, migrations.RunPython.noop),
    ]
