from django.db import migrations, models


def seed_page_copies(apps, schema_editor):
    ServicesPageCopy = apps.get_model("core", "ServicesPageCopy")
    StorePageCopy = apps.get_model("core", "StorePageCopy")
    ServicesPageCopy.objects.get_or_create(singleton_id=1)
    StorePageCopy.objects.get_or_create(singleton_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0048_home_page_copy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ServicesPageCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_id", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("meta_title", models.CharField(default="Bad Guy Motors — Upgrades & Booking", max_length=160)),
                (
                    "meta_description",
                    models.TextField(
                        default="Browse detailing, protection, and performance services with live pricing from Bad Guy Motors."
                    ),
                ),
                ("skip_to_main_label", models.CharField(default="Skip to main content", max_length=120)),
                ("brand_word_white", models.CharField(default="BAD GUY", max_length=40)),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                ("brand_tagline", models.CharField(default="CUSTOM BUILDS • INSTALLS • UPGRADES", max_length=120)),
                ("nav_toggle_label", models.CharField(default="Toggle navigation", max_length=80)),
                ("nav_services_label", models.CharField(default="Services", max_length=40)),
                ("nav_client_portal_label", models.CharField(default="Client Portal", max_length=60)),
                ("nav_login_label", models.CharField(default="Login", max_length=40)),
                ("nav_products_label", models.CharField(default="Products", max_length=40)),
                ("nav_merch_label", models.CharField(default="Merch", max_length=40)),
                ("nav_merch_badge", models.CharField(default="Soon", max_length=20)),
                ("nav_dealers_label", models.CharField(default="Dealers", max_length=40)),
                ("nav_financing_label", models.CharField(default="Financing", max_length=40)),
                ("nav_about_label", models.CharField(default="About", max_length=40)),
                ("hero_title", models.CharField(default="Built to be bad. Engineered to last.", max_length=140)),
                (
                    "hero_lead",
                    models.TextField(
                        default="Book custom fabrication, diesel performance, coatings, body swaps and more — bumpers, headache & chase racks, mudflaps, running boards, fender flares, lift kits & 4‑links, tuning, and installs."
                    ),
                ),
                ("hero_cta_label", models.CharField(default="Browse services ↓", max_length=80)),
                ("section_title", models.CharField(default="Upgrades & Services", max_length=80)),
                ("search_placeholder", models.CharField(default="Search a service…", max_length=120)),
                ("filter_all_categories_label", models.CharField(default="All categories", max_length=60)),
                ("search_button_label", models.CharField(default="Search", max_length=40)),
                ("reset_button_label", models.CharField(default="Reset", max_length=40)),
                ("search_results_label", models.CharField(default="Search results", max_length=60)),
                ("live_no_results_label", models.CharField(default="No services found.", max_length=80)),
                (
                    "live_error_label",
                    models.CharField(default="Could not load results. Please try again.", max_length=120),
                ),
                ("search_no_results_prefix", models.CharField(default="No results for", max_length=80)),
                ("search_no_results_suffix", models.CharField(default=".", max_length=40)),
                ("category_empty_label", models.CharField(default="No services in this category yet.", max_length=120)),
                ("uncategorized_title", models.CharField(default="Uncategorized", max_length=80)),
                ("catalog_empty_label", models.CharField(default="The catalog will be available soon 👍", max_length=140)),
                ("service_image_aria_label", models.CharField(default="Service image", max_length=80)),
                ("service_image_fallback_label", models.CharField(default="BGM • SERVICE", max_length=40)),
                ("book_aria_prefix", models.CharField(default="Book", max_length=40)),
                ("pick_time_label", models.CharField(default="Pick a time", max_length=60)),
                ("contact_for_estimate_label", models.CharField(default="Contact for estimate", max_length=80)),
                ("from_label", models.CharField(default="From", max_length=40)),
                ("duration_separator", models.CharField(default="·", max_length=8)),
                ("duration_unit", models.CharField(default="min", max_length=20)),
                ("booking_modal_title_prefix", models.CharField(default="Booking for", max_length=80)),
                ("booking_close_label", models.CharField(default="Close", max_length=40)),
                ("booking_staff_label", models.CharField(default="Staff", max_length=40)),
                ("booking_staff_picker_label", models.CharField(default="Pick a staff member", max_length=80)),
                ("booking_choose_time_label", models.CharField(default="Choose time", max_length=60)),
                ("booking_prev_label", models.CharField(default="← Prev", max_length=20)),
                ("booking_today_label", models.CharField(default="Today", max_length=20)),
                ("booking_next_label", models.CharField(default="Next →", max_length=20)),
                ("booking_mobile_day_label", models.CharField(default="Day", max_length=20)),
                ("booking_mobile_pick_day_label", models.CharField(default="Pick a day", max_length=60)),
                ("booking_jump_today_label", models.CharField(default="Jump to today", max_length=60)),
                ("booking_available_times_label", models.CharField(default="Available times", max_length=60)),
                ("booking_no_open_times_label", models.CharField(default="No open times for this day.", max_length=120)),
                ("booking_no_open_times_on_prefix", models.CharField(default="No open times on", max_length=80)),
                ("booking_no_open_times_on_suffix", models.CharField(default=".", max_length=20)),
                ("booking_no_availability_label", models.CharField(default="No availability yet", max_length=80)),
                (
                    "booking_scroll_hint_desktop",
                    models.CharField(
                        default="Shift + scroll for horizontal scroll. Red = busy (unclickable).",
                        max_length=200,
                    ),
                ),
                (
                    "booking_scroll_hint_mobile",
                    models.CharField(
                        default="Swipe left/right to see more days. Red = busy (unclickable).",
                        max_length=200,
                    ),
                ),
                ("booking_summary_label", models.CharField(default="Summary", max_length=40)),
                ("booking_summary_default", models.CharField(default="Pick a staff member and time.", max_length=120)),
                ("booking_summary_staff_prefix", models.CharField(default="Staff:", max_length=40)),
                ("booking_summary_time_prefix", models.CharField(default="Time:", max_length=40)),
                ("booking_summary_time_selected_label", models.CharField(default="Time selected.", max_length=80)),
                ("booking_full_name_label", models.CharField(default="Full name*", max_length=60)),
                ("booking_full_name_placeholder", models.CharField(default="John Doe", max_length=120)),
                ("booking_email_label", models.CharField(default="Email*", max_length=40)),
                ("booking_email_placeholder", models.CharField(default="you@example.com", max_length=120)),
                ("booking_phone_label", models.CharField(default="Phone*", max_length=40)),
                ("booking_phone_placeholder", models.CharField(default="+1 5551234567", max_length=120)),
                ("booking_phone_title", models.CharField(default="Use digits only, optionally starting with +", max_length=120)),
                (
                    "booking_confirmation_hint",
                    models.CharField(
                        default="No account needed — we confirm bookings by email and phone.",
                        max_length=160,
                    ),
                ),
                ("booking_cancel_label", models.CharField(default="Cancel", max_length=40)),
                ("booking_confirm_label", models.CharField(default="Confirm booking", max_length=60)),
                ("booking_no_staff_label", models.CharField(default="No staff available", max_length=80)),
                ("booking_availability_error_label", models.CharField(default="Unable to fetch availability", max_length=120)),
                ("booking_failed_slots_label", models.CharField(default="Failed to load available slots", max_length=120)),
                (
                    "booking_missing_contact_error",
                    models.CharField(default="Please add your name, email and phone.", max_length=120),
                ),
                ("booking_create_error_label", models.CharField(default="Could not create an appointment", max_length=120)),
                ("booking_created_label", models.CharField(default="Appointment created!", max_length=80)),
                ("booking_time_label", models.CharField(default="Time:", max_length=40)),
                ("booking_error_label", models.CharField(default="Booking error", max_length=80)),
                ("contact_fab_label", models.CharField(default="Contact us", max_length=60)),
                ("contact_modal_title", models.CharField(default="Contact us", max_length=60)),
                ("contact_close_label", models.CharField(default="Close", max_length=40)),
                ("contact_email_label", models.CharField(default="E-mail", max_length=40)),
                ("contact_phone_label", models.CharField(default="Phone", max_length=40)),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                ("contact_copy_success_label", models.CharField(default="Copied", max_length=40)),
                ("contact_copy_failed_label", models.CharField(default="Copy failed", max_length=40)),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                ("contact_write_email_label", models.CharField(default="Write e-mail", max_length=60)),
                ("contact_text_label", models.CharField(default="Text us", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Services page copy",
                "verbose_name_plural": "Services page copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.CreateModel(
            name="StorePageCopy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("singleton_id", models.PositiveSmallIntegerField(default=1, editable=False, unique=True)),
                ("page_title", models.CharField(default="BGM — Products", max_length=160)),
                ("meta_title", models.CharField(default="BGM Customs — Storefront", max_length=160)),
                (
                    "meta_description",
                    models.TextField(
                        default="Shop curated parts, aero, lighting, and performance upgrades from BGM Customs."
                    ),
                ),
                ("brand_word_white", models.CharField(default="BAD GUY", max_length=40)),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                ("brand_tagline", models.CharField(default="CUSTOM BUILDS • INSTALLS • UPGRADES", max_length=120)),
                ("nav_toggle_label", models.CharField(default="Toggle navigation", max_length=80)),
                ("nav_services_label", models.CharField(default="Services", max_length=40)),
                ("nav_client_portal_label", models.CharField(default="Client Portal", max_length=60)),
                ("nav_login_label", models.CharField(default="Login", max_length=40)),
                ("nav_products_label", models.CharField(default="Products", max_length=40)),
                ("nav_merch_label", models.CharField(default="Merch", max_length=40)),
                ("nav_merch_badge", models.CharField(default="Soon", max_length=20)),
                ("nav_dealers_label", models.CharField(default="Dealers", max_length=40)),
                ("nav_financing_label", models.CharField(default="Financing", max_length=40)),
                ("nav_about_label", models.CharField(default="About", max_length=40)),
                ("hero_title", models.CharField(default="Parts & Upgrades", max_length=80)),
                ("hero_lead", models.CharField(default="Performance parts curated by BGM.", max_length=160)),
                ("hero_primary_cta_label", models.CharField(default="Book install", max_length=60)),
                ("hero_secondary_cta_label", models.CharField(default="Open cart", max_length=60)),
                (
                    "hero_disclaimer_fallback",
                    models.CharField(default="Product may not appear exactly as shown.", max_length=140),
                ),
                ("filters_toggle_label", models.CharField(default="Filters", max_length=40)),
                ("filters_active_badge", models.CharField(default="Active", max_length=20)),
                ("filters_reset_label", models.CharField(default="Reset", max_length=40)),
                ("filters_heading", models.CharField(default="Filters", max_length=40)),
                ("filters_close_label", models.CharField(default="Close", max_length=40)),
                ("filters_category_label", models.CharField(default="Category", max_length=40)),
                ("filters_make_label", models.CharField(default="Make", max_length=40)),
                ("filters_model_label", models.CharField(default="Model", max_length=40)),
                ("filters_year_label", models.CharField(default="Year", max_length=40)),
                ("filters_apply_label", models.CharField(default="Apply filters", max_length=60)),
                ("filters_clear_label", models.CharField(default="Clear", max_length=40)),
                ("categories_title", models.CharField(default="Categories", max_length=60)),
                ("categories_desc", models.CharField(default="Pick a category to explore", max_length=80)),
                ("categories_empty_label", models.CharField(default="No categories yet.", max_length=80)),
                ("results_title", models.CharField(default="Results", max_length=60)),
                ("results_desc", models.CharField(default="Filtered products", max_length=80)),
                ("results_empty_label", models.CharField(default="No products found.", max_length=80)),
                ("new_arrivals_title", models.CharField(default="New arrivals", max_length=60)),
                ("new_arrivals_cart_label", models.CharField(default="Cart", max_length=40)),
                ("browse_title", models.CharField(default="Browse by category", max_length=80)),
                ("browse_desc", models.CharField(default="Explore all categories", max_length=80)),
                ("browse_view_all_label", models.CharField(default="View all", max_length=40)),
                ("contact_for_estimate_label", models.CharField(default="Contact for estimate", max_length=80)),
                ("from_label", models.CharField(default="From", max_length=40)),
                ("dealer_label", models.CharField(default="Dealer", max_length=40)),
                ("save_label", models.CharField(default="Save", max_length=40)),
                ("contact_fab_label", models.CharField(default="Contact us", max_length=60)),
                ("contact_modal_title", models.CharField(default="Contact us", max_length=60)),
                ("contact_close_label", models.CharField(default="Close", max_length=40)),
                ("contact_email_label", models.CharField(default="E-mail", max_length=40)),
                ("contact_phone_label", models.CharField(default="Phone", max_length=40)),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                ("contact_copy_success_label", models.CharField(default="Copied", max_length=40)),
                ("contact_copy_failed_label", models.CharField(default="Copy failed", max_length=40)),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                ("contact_write_email_label", models.CharField(default="Write e-mail", max_length=60)),
                ("contact_text_label", models.CharField(default="Text us", max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Store page copy",
                "verbose_name_plural": "Store page copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.RunPython(seed_page_copies, migrations.RunPython.noop),
    ]
