# Generated by Django 5.1.6 on 2026-01-26 04:32

from django.db import migrations, models


def seed_page_copies(apps, schema_editor):
    ClientPortalPageCopy = apps.get_model("core", "ClientPortalPageCopy")
    MerchPageCopy = apps.get_model("core", "MerchPageCopy")
    ClientPortalPageCopy.objects.get_or_create(singleton_id=1)
    MerchPageCopy.objects.get_or_create(singleton_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_services_store_page_copy"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientPortalPageCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        default="Bad Guy Motors | Client Portal", max_length=160
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="Bad Guy Motors | Client Portal", max_length=160
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Manage appointments, check project status, and review invoices in the client portal."
                    ),
                ),
                ("brand_mark", models.CharField(default="BGM", max_length=20)),
                (
                    "brand_name",
                    models.CharField(default="Client Portal", max_length=80),
                ),
                ("mobile_menu_label", models.CharField(default="Menu", max_length=40)),
                (
                    "mobile_controls_aria_label",
                    models.CharField(default="Portal controls", max_length=80),
                ),
                (
                    "sidebar_close_label",
                    models.CharField(default="Close menu", max_length=40),
                ),
                (
                    "nav_overview_label",
                    models.CharField(default="Overview", max_length=40),
                ),
                (
                    "nav_appointments_label",
                    models.CharField(default="Appointments", max_length=60),
                ),
                ("nav_orders_label", models.CharField(default="Orders", max_length=40)),
                ("nav_files_label", models.CharField(default="Files", max_length=40)),
                (
                    "nav_notifications_label",
                    models.CharField(default="Notifications", max_length=60),
                ),
                (
                    "nav_profile_label",
                    models.CharField(default="Profile", max_length=40),
                ),
                (
                    "nav_back_home_label",
                    models.CharField(default="Back to Home", max_length=60),
                ),
                (
                    "nav_sign_out_label",
                    models.CharField(default="Sign out", max_length=40),
                ),
                (
                    "welcome_back_prefix",
                    models.CharField(default="Welcome back,", max_length=80),
                ),
                ("welcome_back_suffix", models.CharField(default=".", max_length=20)),
                (
                    "dashboard_kicker",
                    models.CharField(
                        default="Keep your builds on schedule. No mercy for missed slots.",
                        max_length=200,
                    ),
                ),
                ("upcoming_title", models.CharField(default="Upcoming", max_length=40)),
                (
                    "upcoming_empty_label",
                    models.CharField(
                        default="No upcoming appointments.", max_length=120
                    ),
                ),
                (
                    "action_cancel_label",
                    models.CharField(default="Cancel", max_length=40),
                ),
                (
                    "action_reschedule_label",
                    models.CharField(default="Reschedule", max_length=60),
                ),
                ("stats_title", models.CharField(default="Stats", max_length=40)),
                (
                    "stats_chart_label",
                    models.CharField(default="Appointments", max_length=60),
                ),
                (
                    "recent_title",
                    models.CharField(default="Recent appointments", max_length=80),
                ),
                (
                    "recent_empty_label",
                    models.CharField(
                        default="No completed appointments yet.", max_length=120
                    ),
                ),
                ("table_date_label", models.CharField(default="Date", max_length=40)),
                (
                    "table_service_label",
                    models.CharField(default="Service", max_length=40),
                ),
                ("table_staff_label", models.CharField(default="Staff", max_length=40)),
                (
                    "table_status_label",
                    models.CharField(default="Status", max_length=40),
                ),
                (
                    "table_amount_label",
                    models.CharField(default="Amount", max_length=40),
                ),
                ("rates_title", models.CharField(default="Rates", max_length=40)),
                (
                    "rates_shop_label",
                    models.CharField(default="Shop rate", max_length=40),
                ),
                ("rates_shop_value", models.CharField(default="130/hr", max_length=40)),
                (
                    "rates_cad_label",
                    models.CharField(default="Design/CAD rate", max_length=60),
                ),
                ("rates_cad_value", models.CharField(default="150/hr", max_length=40)),
                (
                    "quick_facts_title",
                    models.CharField(default="Quick facts", max_length=60),
                ),
                (
                    "quick_fact_1",
                    models.CharField(
                        default="Alberta-made parts, built in Medicine Hat",
                        max_length=160,
                    ),
                ),
                (
                    "quick_fact_2",
                    models.CharField(
                        default="Custom fabrication, diesel performance, coatings",
                        max_length=160,
                    ),
                ),
                (
                    "quick_fact_3",
                    models.CharField(
                        default="Warranty & aftercare included with every build",
                        max_length=160,
                    ),
                ),
                (
                    "policies_title",
                    models.CharField(default="Shop info & policies", max_length=80),
                ),
                (
                    "policy_item_1",
                    models.CharField(
                        default="Deposits secure your slot; balances due on delivery.",
                        max_length=200,
                    ),
                ),
                (
                    "policy_item_2",
                    models.CharField(
                        default="Storage fees may apply for completed items not picked up in a timely manner.",
                        max_length=200,
                    ),
                ),
                (
                    "policy_item_3",
                    models.CharField(
                        default="We use DOM tubing, quality hardware, and proven components.",
                        max_length=200,
                    ),
                ),
                (
                    "policy_item_4",
                    models.CharField(
                        default="Transparent timelines with progress updates in your portal.",
                        max_length=200,
                    ),
                ),
                (
                    "care_title",
                    models.CharField(default="Care & warranty", max_length=80),
                ),
                (
                    "care_item_1",
                    models.CharField(
                        default="Torque checks after install; follow-up available by appointment.",
                        max_length=200,
                    ),
                ),
                (
                    "care_item_2",
                    models.CharField(
                        default="Coatings (Armadillo / Smooth Criminal Liner): mild soap, soft brush; avoid harsh solvents.",
                        max_length=240,
                    ),
                ),
                (
                    "care_item_3",
                    models.CharField(
                        default="We stand behind our work—if something isn’t right, tell us and we’ll make it right.",
                        max_length=200,
                    ),
                ),
                (
                    "appointments_title",
                    models.CharField(default="My appointments", max_length=60),
                ),
                (
                    "appointments_book_label",
                    models.CharField(default="+ Book", max_length=40),
                ),
                (
                    "appointments_completed_label",
                    models.CharField(default="Completed", max_length=40),
                ),
                (
                    "appointments_empty_label",
                    models.CharField(default="No appointments.", max_length=80),
                ),
                ("orders_title", models.CharField(default="My orders", max_length=60)),
                (
                    "orders_go_to_products_label",
                    models.CharField(default="Go to products", max_length=60),
                ),
                (
                    "orders_empty_label",
                    models.CharField(default="No orders yet.", max_length=80),
                ),
                ("files_title", models.CharField(default="Files", max_length=60)),
                (
                    "files_lead",
                    models.CharField(
                        default="Upload insurance papers, IDs, or inspiration photos for our team.",
                        max_length=200,
                    ),
                ),
                (
                    "files_max_size_label",
                    models.CharField(default="Max size:", max_length=40),
                ),
                (
                    "files_description_label",
                    models.CharField(default="Description (optional)", max_length=60),
                ),
                (
                    "files_description_placeholder",
                    models.CharField(default="e.g. Insurance approval", max_length=120),
                ),
                (
                    "files_dropzone_title",
                    models.CharField(
                        default="Drop a file here or click to browse", max_length=120
                    ),
                ),
                (
                    "files_accepted_prefix",
                    models.CharField(
                        default="Accepted: images (JPG, PNG, WEBP, HEIC) or PDF. Max ",
                        max_length=180,
                    ),
                ),
                (
                    "files_accepted_suffix",
                    models.CharField(default=" MB.", max_length=40),
                ),
                (
                    "files_choose_label",
                    models.CharField(default="Choose file", max_length=40),
                ),
                (
                    "files_your_files_title",
                    models.CharField(default="Your files", max_length=60),
                ),
                (
                    "files_total_suffix",
                    models.CharField(default="total", max_length=20),
                ),
                (
                    "files_empty_label",
                    models.CharField(
                        default="No files yet. Upload your first document or photo.",
                        max_length=160,
                    ),
                ),
                (
                    "files_remove_label",
                    models.CharField(default="Remove", max_length=40),
                ),
                (
                    "files_file_fallback_label",
                    models.CharField(default="File", max_length=40),
                ),
                (
                    "notifications_title",
                    models.CharField(default="Notifications", max_length=60),
                ),
                (
                    "notifications_empty_label",
                    models.CharField(default="Coming soon.", max_length=80),
                ),
                ("profile_title", models.CharField(default="Profile", max_length=60)),
                (
                    "profile_first_name_label",
                    models.CharField(default="First name", max_length=40),
                ),
                (
                    "profile_last_name_label",
                    models.CharField(default="Last name", max_length=40),
                ),
                (
                    "profile_phone_label",
                    models.CharField(default="Phone", max_length=40),
                ),
                (
                    "profile_email_label",
                    models.CharField(default="E-mail", max_length=40),
                ),
                (
                    "profile_birth_date_label",
                    models.CharField(default="Birth date", max_length=40),
                ),
                (
                    "profile_save_label",
                    models.CharField(default="Save changes", max_length=60),
                ),
                (
                    "reschedule_modal_title",
                    models.CharField(default="Reschedule appointment", max_length=80),
                ),
                (
                    "reschedule_close_label",
                    models.CharField(default="Close", max_length=40),
                ),
                (
                    "reschedule_staff_label",
                    models.CharField(default="Staff", max_length=40),
                ),
                (
                    "reschedule_choose_time_label",
                    models.CharField(default="Choose time", max_length=60),
                ),
                (
                    "reschedule_prev_label",
                    models.CharField(default="← Prev", max_length=20),
                ),
                (
                    "reschedule_today_label",
                    models.CharField(default="Today", max_length=20),
                ),
                (
                    "reschedule_next_label",
                    models.CharField(default="Next →", max_length=20),
                ),
                (
                    "reschedule_shift_scroll_hint",
                    models.CharField(
                        default="Shift+Scroll gives horizontal scrolling. Gray slots are already booked.",
                        max_length=160,
                    ),
                ),
                (
                    "reschedule_cancel_label",
                    models.CharField(default="Cancel", max_length=40),
                ),
                (
                    "reschedule_save_label",
                    models.CharField(default="Save", max_length=40),
                ),
                (
                    "reschedule_no_techs_label",
                    models.CharField(default="No techs available", max_length=80),
                ),
                (
                    "reschedule_no_availability_label",
                    models.CharField(default="No availability", max_length=80),
                ),
                (
                    "reschedule_fetch_error_label",
                    models.CharField(
                        default="Unable to fetch availability", max_length=120
                    ),
                ),
                (
                    "reschedule_failed_slots_label",
                    models.CharField(default="Failed to load slots", max_length=120),
                ),
                (
                    "reschedule_success_prefix",
                    models.CharField(default="Rescheduled to ", max_length=80),
                ),
                (
                    "reschedule_failed_label",
                    models.CharField(default="Reschedule failed", max_length=80),
                ),
                (
                    "cancel_confirm_message",
                    models.CharField(
                        default="Cancel this appointment?", max_length=120
                    ),
                ),
                (
                    "cancel_error_prefix",
                    models.CharField(default="Cancel error: ", max_length=80),
                ),
                (
                    "files_removing_label",
                    models.CharField(default="Removing…", max_length=60),
                ),
                (
                    "files_removed_label",
                    models.CharField(default="File removed.", max_length=80),
                ),
                (
                    "files_delete_failed_label",
                    models.CharField(default="Delete failed.", max_length=80),
                ),
                (
                    "files_delete_error_label",
                    models.CharField(default="Unable to delete file.", max_length=120),
                ),
                (
                    "files_uploading_label",
                    models.CharField(default="Uploading…", max_length=60),
                ),
                (
                    "files_upload_success_label",
                    models.CharField(default="Uploaded successfully.", max_length=80),
                ),
                (
                    "files_upload_failed_label",
                    models.CharField(default="Upload failed.", max_length=80),
                ),
                (
                    "files_too_large_prefix",
                    models.CharField(default="File exceeds ", max_length=80),
                ),
                (
                    "files_too_large_suffix",
                    models.CharField(default=" MB limit.", max_length=40),
                ),
                (
                    "contact_fab_label",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_modal_title",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_close_label",
                    models.CharField(default="Close", max_length=40),
                ),
                (
                    "contact_email_label",
                    models.CharField(default="E-mail", max_length=40),
                ),
                (
                    "contact_phone_label",
                    models.CharField(default="Phone", max_length=40),
                ),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                (
                    "contact_copy_success_label",
                    models.CharField(default="Copied", max_length=40),
                ),
                (
                    "contact_copy_failed_label",
                    models.CharField(default="Copy failed", max_length=40),
                ),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                (
                    "contact_write_email_label",
                    models.CharField(default="Write e-mail", max_length=60),
                ),
                (
                    "contact_text_label",
                    models.CharField(default="Text us", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Client portal copy",
                "verbose_name_plural": "Client portal copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.CreateModel(
            name="MerchPageCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "page_title",
                    models.CharField(
                        default="BGM Customs — Merch (Coming Soon)", max_length=160
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="BGM Customs — Merch (Coming Soon)", max_length=160
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Streetwear, track gear, and pit essentials from BGM Customs are on the way. Join the drop list."
                    ),
                ),
                (
                    "skip_to_main_label",
                    models.CharField(default="Skip to main content", max_length=120),
                ),
                (
                    "brand_word_white",
                    models.CharField(default="BAD GUY", max_length=40),
                ),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                (
                    "brand_tagline",
                    models.CharField(
                        default="CUSTOM BUILDS • INSTALLS • UPGRADES", max_length=120
                    ),
                ),
                (
                    "nav_toggle_label",
                    models.CharField(default="Toggle navigation", max_length=80),
                ),
                (
                    "nav_services_label",
                    models.CharField(default="Services", max_length=40),
                ),
                (
                    "nav_client_portal_label",
                    models.CharField(default="Client Portal", max_length=60),
                ),
                ("nav_login_label", models.CharField(default="Login", max_length=40)),
                (
                    "nav_products_label",
                    models.CharField(default="Products", max_length=40),
                ),
                ("nav_merch_label", models.CharField(default="Merch", max_length=40)),
                ("nav_merch_badge", models.CharField(default="Soon", max_length=20)),
                (
                    "nav_dealers_label",
                    models.CharField(default="Dealers", max_length=40),
                ),
                (
                    "nav_financing_label",
                    models.CharField(default="Financing", max_length=40),
                ),
                ("nav_about_label", models.CharField(default="About", max_length=40)),
                ("hero_kicker", models.CharField(default="BGM Merch", max_length=60)),
                (
                    "hero_title",
                    models.CharField(
                        default="Apparel & accessories — Coming soon", max_length=140
                    ),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        default="Tees, hoodies, caps, wall art — built with the same no-compromise mindset. Want first drop access? Stay tuned."
                    ),
                ),
                (
                    "hero_primary_cta_label",
                    models.CharField(default="← Back to Home", max_length=60),
                ),
                (
                    "hero_secondary_cta_label",
                    models.CharField(default="Explore Services", max_length=60),
                ),
                (
                    "hero_disclaimer_fallback",
                    models.CharField(
                        default="Product may not appear exactly as shown.",
                        max_length=140,
                    ),
                ),
                (
                    "section_title",
                    models.CharField(default="First drop ideas", max_length=80),
                ),
                (
                    "section_desc",
                    models.CharField(
                        default="We’re sampling cuts, fabrics and prints.",
                        max_length=120,
                    ),
                ),
                ("section_badge_label", models.CharField(default="WIP", max_length=20)),
                ("card_1_title", models.CharField(default="T-Shirts", max_length=60)),
                (
                    "card_1_desc",
                    models.CharField(
                        default="Heavyweight cotton, oversized fit.", max_length=120
                    ),
                ),
                ("card_2_title", models.CharField(default="Hoodies", max_length=60)),
                (
                    "card_2_desc",
                    models.CharField(
                        default="Brushed fleece, embroidered logos.", max_length=120
                    ),
                ),
                ("card_3_title", models.CharField(default="Caps", max_length=60)),
                (
                    "card_3_desc",
                    models.CharField(
                        default="Low-profile, structured.", max_length=120
                    ),
                ),
                ("card_4_title", models.CharField(default="Posters", max_length=60)),
                (
                    "card_4_desc",
                    models.CharField(
                        default="Garage & office wall essentials.", max_length=120
                    ),
                ),
                ("bottom_cta_label", models.CharField(default="← Home", max_length=40)),
                (
                    "contact_fab_label",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_modal_title",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_close_label",
                    models.CharField(default="Close", max_length=40),
                ),
                (
                    "contact_email_label",
                    models.CharField(default="E-mail", max_length=40),
                ),
                (
                    "contact_phone_label",
                    models.CharField(default="Phone", max_length=40),
                ),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                (
                    "contact_copy_success_label",
                    models.CharField(default="Copied", max_length=40),
                ),
                (
                    "contact_copy_failed_label",
                    models.CharField(default="Copy failed", max_length=40),
                ),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                (
                    "contact_write_email_label",
                    models.CharField(default="Write e-mail", max_length=60),
                ),
                (
                    "contact_text_label",
                    models.CharField(default="Text us", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Merch page copy",
                "verbose_name_plural": "Merch page copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.RenameIndex(
            model_name="sitenoticesignup",
            new_name="core_siteno_welcome_3db304_idx",
            old_name="core_sit_not_welc_81d49c_idx",
        ),
        migrations.RenameIndex(
            model_name="sitenoticesignup",
            new_name="core_siteno_followu_9188dd_idx",
            old_name="core_sit_not_foll_2_5c8c0b_idx",
        ),
        migrations.RenameIndex(
            model_name="sitenoticesignup",
            new_name="core_siteno_followu_b276d8_idx",
            old_name="core_sit_not_foll_3_eb6a87_idx",
        ),
        migrations.RunPython(seed_page_copies, migrations.RunPython.noop),
    ]
