# Generated by Django 5.1.6 on 2026-01-26 04:59

from django.db import migrations, models


def seed_page_copies(apps, schema_editor):
    AboutPageCopy = apps.get_model("core", "AboutPageCopy")
    DealerStatusPageCopy = apps.get_model("core", "DealerStatusPageCopy")
    FinancingPageCopy = apps.get_model("core", "FinancingPageCopy")
    AboutPageCopy.objects.get_or_create(singleton_id=1)
    DealerStatusPageCopy.objects.get_or_create(singleton_id=1)
    FinancingPageCopy.objects.get_or_create(singleton_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_clientportalpagecopy_merchpagecopy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutPageCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="Bad Guy Motors — Our Story", max_length=160
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Family-run fabrication and diesel performance shop crafting racks, bumpers, coatings, and full builds out of Medicine Hat, AB."
                    ),
                ),
                (
                    "skip_to_main_label",
                    models.CharField(default="Skip to main content", max_length=120),
                ),
                (
                    "brand_word_white",
                    models.CharField(default="BAD GUY", max_length=40),
                ),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                (
                    "brand_tagline",
                    models.CharField(
                        default="CUSTOM BUILDS • INSTALLS • UPGRADES", max_length=120
                    ),
                ),
                (
                    "nav_toggle_label",
                    models.CharField(default="Toggle navigation", max_length=80),
                ),
                (
                    "nav_services_label",
                    models.CharField(default="Services", max_length=40),
                ),
                (
                    "nav_client_portal_label",
                    models.CharField(default="Client Portal", max_length=60),
                ),
                ("nav_login_label", models.CharField(default="Login", max_length=40)),
                (
                    "nav_products_label",
                    models.CharField(default="Products", max_length=40),
                ),
                ("nav_merch_label", models.CharField(default="Merch", max_length=40)),
                ("nav_merch_badge", models.CharField(default="Soon", max_length=20)),
                (
                    "nav_dealers_label",
                    models.CharField(default="Dealers", max_length=40),
                ),
                (
                    "nav_financing_label",
                    models.CharField(default="Financing", max_length=40),
                ),
                ("nav_about_label", models.CharField(default="About", max_length=40)),
                (
                    "hero_title",
                    models.CharField(
                        default="From Bad Guys to Builders.", max_length=120
                    ),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        default="We took the long road — and turned it into horsepower. Bad Guy Motors is a family-run custom fabrication and diesel performance shop in Medicine Hat, AB. We build tough parts, tougher rigs, and a legacy for our kids — from bumpers and racks to fender flares and full builds."
                    ),
                ),
                (
                    "hero_chip_1",
                    models.CharField(default="Family owned", max_length=60),
                ),
                (
                    "hero_chip_2",
                    models.CharField(default="Alberta-made", max_length=60),
                ),
                ("hero_chip_3", models.CharField(default="Custom only", max_length=60)),
                (
                    "hero_image_alt",
                    models.CharField(default="About hero", max_length=80),
                ),
                (
                    "hero_disclaimer",
                    models.CharField(
                        default="Product may not appear exactly as shown.",
                        max_length=140,
                    ),
                ),
                ("story_title", models.CharField(default="Our story", max_length=80)),
                (
                    "story_paragraph_1",
                    models.TextField(
                        default="Co-owners Denim and KC Savoie built Bad Guy Motors after a full 360 — from hard pasts to a focused future. With two kids and two stepkids, we’re a power couple who put family first and quality second to none. We set out to create the shop we wished existed: transparent, disciplined, and obsessed with doing things right."
                    ),
                ),
                (
                    "story_paragraph_2",
                    models.TextField(
                        default="Every build is personal: the parts we design, the welds we lay, the timelines we keep. We want our daughters to see what it means to run a business with grit, integrity, and pride."
                    ),
                ),
                (
                    "build_title",
                    models.CharField(default="What we build", max_length=80),
                ),
                (
                    "build_item_1",
                    models.CharField(default="Bumpers & winch mounts", max_length=120),
                ),
                (
                    "build_item_2",
                    models.CharField(default="Headache & chase racks", max_length=120),
                ),
                (
                    "build_item_3",
                    models.CharField(
                        default="Mudflaps & running boards", max_length=120
                    ),
                ),
                (
                    "build_item_4",
                    models.CharField(default="Fender flares", max_length=120),
                ),
                (
                    "build_item_5",
                    models.CharField(
                        default="Lift kits & 4-link suspensions", max_length=120
                    ),
                ),
                (
                    "build_item_6",
                    models.CharField(
                        default="Diesel performance, tuning & hard parts",
                        max_length=140,
                    ),
                ),
                (
                    "build_item_7",
                    models.CharField(default="Body swaps & custom fab", max_length=120),
                ),
                (
                    "build_item_8",
                    models.CharField(
                        default="Coatings & liners (Armadillo, Smooth Criminal)",
                        max_length=140,
                    ),
                ),
                ("how_title", models.CharField(default="How we work", max_length=80)),
                (
                    "how_step_1_title",
                    models.CharField(default="Consult & scope", max_length=80),
                ),
                (
                    "how_step_1_desc",
                    models.CharField(
                        default="goals, budget, timeline.", max_length=120
                    ),
                ),
                (
                    "how_step_2_title",
                    models.CharField(default="Design & quote", max_length=80),
                ),
                (
                    "how_step_2_desc",
                    models.CharField(
                        default="CAD as needed, milestones, written estimate.",
                        max_length=140,
                    ),
                ),
                (
                    "how_step_3_title",
                    models.CharField(default="Fabricate & update", max_length=80),
                ),
                (
                    "how_step_3_desc",
                    models.CharField(
                        default="progress pics, approvals, clear comms.", max_length=140
                    ),
                ),
                (
                    "how_step_4_title",
                    models.CharField(default="Delivery & aftercare", max_length=80),
                ),
                (
                    "how_step_4_desc",
                    models.CharField(
                        default="test drive, torque check, care guide.", max_length=140
                    ),
                ),
                (
                    "rates_title",
                    models.CharField(default="Rates & policies", max_length=80),
                ),
                (
                    "rates_shop_label",
                    models.CharField(default="Shop rate", max_length=60),
                ),
                ("rates_shop_value", models.CharField(default="130/hr", max_length=40)),
                (
                    "rates_cad_label",
                    models.CharField(default="Design/CAD rate", max_length=60),
                ),
                ("rates_cad_value", models.CharField(default="150/hr", max_length=40)),
                (
                    "rates_policy_1",
                    models.CharField(
                        default="Deposits secure your slot; balance due on delivery.",
                        max_length=160,
                    ),
                ),
                (
                    "rates_policy_2",
                    models.CharField(
                        default="Storage fees may apply for completed items not picked up promptly.",
                        max_length=180,
                    ),
                ),
                (
                    "rates_policy_3",
                    models.CharField(
                        default="Warranty & support — if it isn’t right, we make it right.",
                        max_length=160,
                    ),
                ),
                (
                    "location_title",
                    models.CharField(default="Where to find us", max_length=80),
                ),
                (
                    "location_address",
                    models.TextField(
                        default="Bad Guy Motors Inc.\n620 Porcelain Ave SE, Medicine Hat, AB T1A 0C2"
                    ),
                ),
                (
                    "location_note",
                    models.CharField(
                        default="Open by appointment. Book online to lock your time.",
                        max_length=160,
                    ),
                ),
                (
                    "location_primary_cta_label",
                    models.CharField(default="Book a service", max_length=60),
                ),
                (
                    "location_secondary_cta_label",
                    models.CharField(default="Client portal", max_length=60),
                ),
                (
                    "amvic_title",
                    models.CharField(default="Licensed by AMVIC", max_length=80),
                ),
                (
                    "amvic_description",
                    models.CharField(
                        default="Bad Guy Motors is a licensed automotive business under the Alberta Motor Vehicle Industry Council.",
                        max_length=200,
                    ),
                ),
                (
                    "contact_fab_label",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_modal_title",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_close_label",
                    models.CharField(default="Close", max_length=40),
                ),
                (
                    "contact_email_label",
                    models.CharField(default="E-mail", max_length=40),
                ),
                (
                    "contact_phone_label",
                    models.CharField(default="Phone", max_length=40),
                ),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                (
                    "contact_copy_success_label",
                    models.CharField(default="Copied", max_length=40),
                ),
                (
                    "contact_copy_failed_label",
                    models.CharField(default="Copy failed", max_length=40),
                ),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                (
                    "contact_write_email_label",
                    models.CharField(default="Write e-mail", max_length=60),
                ),
                (
                    "contact_text_label",
                    models.CharField(default="Text us", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About page copy",
                "verbose_name_plural": "About page copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.CreateModel(
            name="DealerStatusPageCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="Dealer Portal — BGM Customs", max_length=160
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Track dealer tier, benefits, and requirements for the BGM Customs wholesale program."
                    ),
                ),
                (
                    "brand_word_white",
                    models.CharField(default="BAD GUY", max_length=40),
                ),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                (
                    "header_badge_label",
                    models.CharField(default="Dealer Portal", max_length=60),
                ),
                ("nav_store_label", models.CharField(default="Store", max_length=40)),
                ("nav_cart_label", models.CharField(default="Cart", max_length=40)),
                (
                    "nav_dealers_label",
                    models.CharField(default="Dealers", max_length=40),
                ),
                (
                    "nav_services_label",
                    models.CharField(default="Services", max_length=60),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(default="BGM Customs", max_length=60),
                ),
                (
                    "hero_title",
                    models.CharField(default="Dealer workspace", max_length=120),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        default="Track your approval status, understand the tier ladder, and jump straight into the catalog with your negotiated pricing."
                    ),
                ),
                (
                    "hero_tier_label_prefix",
                    models.CharField(default="Tier:", max_length=40),
                ),
                (
                    "tier_default_label",
                    models.CharField(default="Standard", max_length=60),
                ),
                (
                    "hero_discount_suffix",
                    models.CharField(default="off catalog", max_length=40),
                ),
                (
                    "hero_primary_cta_label",
                    models.CharField(default="Browse catalog", max_length=60),
                ),
                (
                    "hero_secondary_cta_label",
                    models.CharField(default="Open cart", max_length=40),
                ),
                (
                    "hero_stat_dealer_since_label",
                    models.CharField(default="Dealer since", max_length=60),
                ),
                (
                    "hero_stat_pending_label",
                    models.CharField(default="Pending activation", max_length=80),
                ),
                (
                    "hero_stat_lifetime_spend_label",
                    models.CharField(default="Lifetime spend", max_length=80),
                ),
                (
                    "hero_stat_next_tier_label",
                    models.CharField(default="Next tier target", max_length=80),
                ),
                (
                    "hero_stat_next_tier_suffix",
                    models.CharField(default="to unlock", max_length=60),
                ),
                (
                    "hero_stat_top_tier_label",
                    models.CharField(default="Top tier unlocked", max_length=80),
                ),
                (
                    "hero_stat_top_tier_value",
                    models.CharField(default="Enjoy the max discount", max_length=120),
                ),
                (
                    "hero_disclaimer",
                    models.CharField(
                        default="Product may not appear exactly as shown.",
                        max_length=140,
                    ),
                ),
                (
                    "account_overview_title",
                    models.CharField(default="Account overview", max_length=80),
                ),
                (
                    "account_overview_badge_label",
                    models.CharField(default="Active", max_length=40),
                ),
                (
                    "account_metric_tier_label",
                    models.CharField(default="Tier", max_length=40),
                ),
                (
                    "account_metric_discount_label",
                    models.CharField(default="Discount", max_length=40),
                ),
                (
                    "account_metric_lifetime_spend_label",
                    models.CharField(default="Lifetime spend", max_length=60),
                ),
                (
                    "account_metric_last_review_label",
                    models.CharField(default="Last review", max_length=60),
                ),
                (
                    "progress_title",
                    models.CharField(default="Progress to next tier", max_length=80),
                ),
                (
                    "progress_max_tier_badge",
                    models.CharField(default="Max tier unlocked", max_length=80),
                ),
                (
                    "progress_top_tier_label",
                    models.CharField(default="Top tier", max_length=40),
                ),
                ("orders_title", models.CharField(default="Orders", max_length=60)),
                (
                    "orders_badge_suffix",
                    models.CharField(default="total", max_length=20),
                ),
                ("orders_open_label", models.CharField(default="Open", max_length=40)),
                (
                    "orders_completed_label",
                    models.CharField(default="Completed", max_length=40),
                ),
                (
                    "orders_most_recent_label",
                    models.CharField(default="Most recent", max_length=60),
                ),
                (
                    "orders_cta_label",
                    models.CharField(default="Place order", max_length=40),
                ),
                (
                    "resources_title",
                    models.CharField(default="Resources", max_length=60),
                ),
                (
                    "resource_1_title",
                    models.CharField(default="Dealer price sheet", max_length=80),
                ),
                (
                    "resource_1_desc",
                    models.CharField(
                        default="Download the latest catalog with your discount baked in.",
                        max_length=160,
                    ),
                ),
                (
                    "resource_1_cta_label",
                    models.CharField(default="Open catalog", max_length=60),
                ),
                (
                    "resource_2_title",
                    models.CharField(default="Support desk", max_length=80),
                ),
                (
                    "resource_2_desc",
                    models.CharField(
                        default="Need to escalate an order or request marketing assets? Reach out.",
                        max_length=180,
                    ),
                ),
                (
                    "resource_2_cta_label",
                    models.CharField(default="Contact support", max_length=60),
                ),
                (
                    "resource_3_title",
                    models.CharField(default="Dealer policy", max_length=80),
                ),
                (
                    "resource_3_desc",
                    models.CharField(
                        default="Review the playbook covering terms, logistics, and reporting cadence.",
                        max_length=180,
                    ),
                ),
                (
                    "resource_3_cta_label",
                    models.CharField(default="View policy", max_length=60),
                ),
                (
                    "application_status_title",
                    models.CharField(default="Application status", max_length=80),
                ),
                (
                    "application_status_not_submitted_badge",
                    models.CharField(default="Not submitted", max_length=60),
                ),
                (
                    "application_pending_callout",
                    models.TextField(
                        default="Thanks for applying. Your submission is in the review queue. We typically respond within 2 business days."
                    ),
                ),
                (
                    "application_rejected_callout",
                    models.TextField(
                        default="The previous request was declined. Feel free to update your details and submit a new application."
                    ),
                ),
                (
                    "application_approved_callout",
                    models.TextField(
                        default="Approved — we are finalizing onboarding. Expect an activation email shortly."
                    ),
                ),
                (
                    "application_none_callout",
                    models.TextField(
                        default="You have not submitted a dealer request yet. Tell us about your business and projected volume to unlock wholesale pricing."
                    ),
                ),
                (
                    "application_metric_business_label",
                    models.CharField(default="Business", max_length=60),
                ),
                (
                    "application_metric_tier_label",
                    models.CharField(default="Requested tier", max_length=60),
                ),
                (
                    "application_metric_submitted_label",
                    models.CharField(default="Submitted", max_length=60),
                ),
                (
                    "application_contact_cta_label",
                    models.CharField(
                        default="Need to update your data? Contact us", max_length=120
                    ),
                ),
                (
                    "application_apply_cta_label",
                    models.CharField(default="Apply now", max_length=40),
                ),
                (
                    "application_reapply_cta_label",
                    models.CharField(default="Reapply", max_length=40),
                ),
                (
                    "tier_ladder_title",
                    models.CharField(default="Tier ladder", max_length=60),
                ),
                (
                    "tier_ladder_badge_label",
                    models.CharField(default="Transparent thresholds", max_length=80),
                ),
                (
                    "tier_table_tier_label",
                    models.CharField(default="Tier", max_length=40),
                ),
                (
                    "tier_table_min_spend_label",
                    models.CharField(default="Minimum spend", max_length=80),
                ),
                (
                    "tier_table_discount_label",
                    models.CharField(default="Discount", max_length=60),
                ),
                (
                    "tier_table_notes_label",
                    models.CharField(default="Notes", max_length=60),
                ),
                (
                    "tier_empty_label",
                    models.CharField(
                        default="Tier configuration is coming soon.", max_length=120
                    ),
                ),
                (
                    "timeline_title",
                    models.CharField(default="Lifecycle timeline", max_length=80),
                ),
                (
                    "timeline_in_progress_label",
                    models.CharField(default="In progress", max_length=60),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Dealer portal copy",
                "verbose_name_plural": "Dealer portal copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.CreateModel(
            name="FinancingPageCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        default="BGM Customs — Financing Options", max_length=160
                    ),
                ),
                (
                    "meta_description",
                    models.TextField(
                        default="Flexible financing partners for builds, parts, and installs including Canadian Financial and Afterpay."
                    ),
                ),
                (
                    "skip_to_main_label",
                    models.CharField(default="Skip to main content", max_length=120),
                ),
                (
                    "brand_word_white",
                    models.CharField(default="BAD GUY", max_length=40),
                ),
                ("brand_word_red", models.CharField(default="MOTORS", max_length=40)),
                (
                    "brand_tagline",
                    models.CharField(
                        default="CUSTOM BUILDS • INSTALLS • UPGRADES", max_length=120
                    ),
                ),
                (
                    "nav_toggle_label",
                    models.CharField(default="Toggle navigation", max_length=80),
                ),
                (
                    "nav_services_label",
                    models.CharField(default="Services", max_length=40),
                ),
                (
                    "nav_client_portal_label",
                    models.CharField(default="Client Portal", max_length=60),
                ),
                ("nav_login_label", models.CharField(default="Login", max_length=40)),
                (
                    "nav_products_label",
                    models.CharField(default="Products", max_length=40),
                ),
                ("nav_merch_label", models.CharField(default="Merch", max_length=40)),
                ("nav_merch_badge", models.CharField(default="Soon", max_length=20)),
                (
                    "nav_dealers_label",
                    models.CharField(default="Dealers", max_length=40),
                ),
                (
                    "nav_financing_label",
                    models.CharField(default="Financing", max_length=40),
                ),
                ("nav_about_label", models.CharField(default="About", max_length=40)),
                (
                    "hero_kicker",
                    models.CharField(default="Flexible Financing", max_length=80),
                ),
                (
                    "hero_title",
                    models.CharField(
                        default="Build now. Pay over time.", max_length=120
                    ),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        default="We offer simple financing options for parts, installs, and full custom builds. Apply in minutes with no impact to your credit score for pre-qualification where available."
                    ),
                ),
                (
                    "hero_primary_cta_label",
                    models.CharField(default="See options", max_length=60),
                ),
                (
                    "hero_secondary_cta_label",
                    models.CharField(default="Explore Services", max_length=80),
                ),
                (
                    "hero_image_alt",
                    models.CharField(default="Financing hero", max_length=80),
                ),
                (
                    "hero_disclaimer",
                    models.CharField(
                        default="Product may not appear exactly as shown.",
                        max_length=140,
                    ),
                ),
                (
                    "providers_title",
                    models.CharField(default="Financing providers", max_length=80),
                ),
                (
                    "providers_desc",
                    models.CharField(
                        default="Pick the option that fits your project size and timeline.",
                        max_length=160,
                    ),
                ),
                (
                    "providers_badge_label",
                    models.CharField(default="Trusted", max_length=40),
                ),
                (
                    "provider_1_title",
                    models.CharField(default="Canadian Financial", max_length=80),
                ),
                (
                    "provider_1_meta",
                    models.CharField(
                        default="Advisor: Canadian Financial team", max_length=120
                    ),
                ),
                (
                    "provider_1_desc",
                    models.TextField(
                        default="Personalized financing support through Canadian Financial. Great for custom quotes and structured plans."
                    ),
                ),
                (
                    "provider_1_primary_cta_label",
                    models.CharField(
                        default="Apply with Canadian Financial", max_length=80
                    ),
                ),
                (
                    "provider_1_secondary_cta_label",
                    models.CharField(default="How it works", max_length=60),
                ),
                (
                    "provider_2_title",
                    models.CharField(default="Afterpay (via Square)", max_length=80),
                ),
                (
                    "provider_2_meta_prefix",
                    models.CharField(default="Good up to ≈", max_length=80),
                ),
                (
                    "provider_2_meta_amount",
                    models.CharField(default="2,000", max_length=20),
                ),
                (
                    "provider_2_desc",
                    models.TextField(
                        default="Split smaller purchases into interest-free payments at checkout. Perfect for parts and minor installs."
                    ),
                ),
                (
                    "provider_2_primary_cta_label",
                    models.CharField(default="Shop parts", max_length=60),
                ),
                (
                    "provider_2_secondary_cta_label",
                    models.CharField(default="Book an install", max_length=60),
                ),
                (
                    "providers_bottom_primary_cta_label",
                    models.CharField(default="← Home", max_length=40),
                ),
                (
                    "providers_bottom_secondary_cta_label",
                    models.CharField(default="See all services", max_length=80),
                ),
                (
                    "steps_title",
                    models.CharField(default="How financing works", max_length=80),
                ),
                (
                    "steps_desc",
                    models.CharField(
                        default="A simple path from quote to approved build.",
                        max_length=120,
                    ),
                ),
                (
                    "step_1_title",
                    models.CharField(default="Get your project quote", max_length=80),
                ),
                (
                    "step_1_desc",
                    models.TextField(
                        default="Talk to our team about your build or parts install. We’ll outline scope, cost, and timeline."
                    ),
                ),
                (
                    "step_2_title",
                    models.CharField(default="Apply with a provider", max_length=80),
                ),
                (
                    "step_2_desc",
                    models.TextField(
                        default="Use Canadian Financial for larger projects, or Afterpay for smaller purchases."
                    ),
                ),
                (
                    "step_3_title",
                    models.CharField(default="Choose terms & finalize", max_length=80),
                ),
                (
                    "step_3_desc",
                    models.TextField(
                        default="Pick the plan that fits your budget. We coordinate approvals and scheduling."
                    ),
                ),
                (
                    "step_4_title",
                    models.CharField(default="Build & updates", max_length=80),
                ),
                (
                    "step_4_desc",
                    models.TextField(
                        default="We get to work. You’ll receive progress updates in your Client Portal."
                    ),
                ),
                ("faq_title", models.CharField(default="Good to know", max_length=80)),
                (
                    "faq_desc",
                    models.CharField(
                        default="Quick answers to common questions.", max_length=120
                    ),
                ),
                (
                    "faq_1_title",
                    models.CharField(
                        default="Credit checks & approvals", max_length=80
                    ),
                ),
                (
                    "faq_1_desc",
                    models.TextField(
                        default="Some providers offer soft credit checks for pre-qualification. Final approval may require a hard check. Terms and limits depend on your credit profile."
                    ),
                ),
                (
                    "faq_2_title",
                    models.CharField(default="Project eligibility", max_length=80),
                ),
                (
                    "faq_2_desc",
                    models.TextField(
                        default="Financing can cover parts, labor, coatings, and custom fabrication. We’ll help you structure the quote to fit provider requirements."
                    ),
                ),
                (
                    "faq_3_title",
                    models.CharField(default="Afterpay limits", max_length=80),
                ),
                (
                    "faq_3_desc_prefix",
                    models.CharField(
                        default="Afterpay via Square is typically suitable for purchases up to about",
                        max_length=140,
                    ),
                ),
                ("faq_3_desc_amount", models.CharField(default="2,000", max_length=20)),
                (
                    "faq_3_desc_suffix",
                    models.CharField(
                        default="and is best used for smaller jobs and parts orders.",
                        max_length=160,
                    ),
                ),
                ("faq_4_title", models.CharField(default="Questions?", max_length=80)),
                (
                    "faq_4_desc",
                    models.TextField(
                        default="Reach out to our team and we’ll walk you through options and next steps."
                    ),
                ),
                (
                    "faq_4_cta_label",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_fab_label",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_modal_title",
                    models.CharField(default="Contact us", max_length=60),
                ),
                (
                    "contact_close_label",
                    models.CharField(default="Close", max_length=40),
                ),
                (
                    "contact_email_label",
                    models.CharField(default="E-mail", max_length=40),
                ),
                (
                    "contact_phone_label",
                    models.CharField(default="Phone", max_length=40),
                ),
                ("contact_copy_label", models.CharField(default="Copy", max_length=40)),
                (
                    "contact_copy_success_label",
                    models.CharField(default="Copied", max_length=40),
                ),
                (
                    "contact_copy_failed_label",
                    models.CharField(default="Copy failed", max_length=40),
                ),
                ("contact_call_label", models.CharField(default="Call", max_length=40)),
                (
                    "contact_write_email_label",
                    models.CharField(default="Write e-mail", max_length=60),
                ),
                (
                    "contact_text_label",
                    models.CharField(default="Text us", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Financing page copy",
                "verbose_name_plural": "Financing page copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.RunPython(seed_page_copies, migrations.RunPython.noop),
    ]
