# Generated by Django 5.1.6 on 2026-01-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_aboutpagecopy_dealerstatuspagecopy_financingpagecopy"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional circular logo shown above the hero copy.",
                null=True,
                upload_to="home/branding/",
            ),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_alt",
            field=models.CharField(
                blank=True,
                default="BGM logo",
                help_text="Accessible alt text for the hero logo image.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_backdrop",
            field=models.ImageField(
                blank=True,
                help_text="Optional backdrop photo displayed behind the circular logo.",
                null=True,
                upload_to="home/branding/",
            ),
        ),
    ]
