from django.db import migrations, models


def seed_email_templates(apps, schema_editor):
    EmailTemplate = apps.get_model("core", "EmailTemplate")

    templates = [
        {
            "slug": "appointment_confirmation",
            "name": "Appointment confirmation",
            "description": "Sent when a booking is confirmed.",
            "subject": "{brand} booking confirmed",
            "preheader": "Appointment {appointment_id} confirmed",
            "title": "Booking confirmed",
            "greeting": "Hi {client_name},",
            "intro": "Thanks for booking with {brand}. Your appointment is confirmed.",
            "notice_title": "",
            "notice": "",
            "footer": "If you need to reschedule, reply to this email and we'll help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "order_confirmation",
            "name": "Order confirmation",
            "description": "Sent after checkout succeeds.",
            "subject": "{brand} order #{order_id} confirmed",
            "preheader": "Order #{order_id} confirmed",
            "title": "Order confirmed",
            "greeting": "Hi {customer_name},",
            "intro": "Thanks for your order with {brand}. We've got it and will follow up shortly.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we'll help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "order_status_processing",
            "name": "Order status: processing",
            "description": "Sent when an order moves to processing.",
            "subject": "{brand} order #{order_id} {order_status}",
            "preheader": "We are preparing your order now.",
            "title": "Order update: processing",
            "greeting": "Hi {customer_name},",
            "intro": "Your order is now in processing. We'll keep you posted as it moves along.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we'll help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "order_status_shipped",
            "name": "Order status: shipped",
            "description": "Sent when an order ships.",
            "subject": "{brand} order #{order_id} {order_status}",
            "preheader": "Your order is on the way.",
            "title": "Order update: shipped",
            "greeting": "Hi {customer_name},",
            "intro": "Your order has shipped and is on the way to you.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we'll help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "order_status_completed",
            "name": "Order status: completed",
            "description": "Sent when an order is completed.",
            "subject": "{brand} order #{order_id} {order_status}",
            "preheader": "Your order is marked complete.",
            "title": "Order update: completed",
            "greeting": "Hi {customer_name},",
            "intro": "Your order is marked complete. Thanks again for choosing us.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we'll help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "order_status_cancelled",
            "name": "Order status: cancelled",
            "description": "Sent when an order is cancelled.",
            "subject": "{brand} order #{order_id} {order_status}",
            "preheader": "Your order was cancelled.",
            "title": "Order update: cancelled",
            "greeting": "Hi {customer_name},",
            "intro": "Your order was cancelled. If this is unexpected, reply to this email and we'll help.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we'll help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "abandoned_cart_1",
            "name": "Abandoned cart (1st)",
            "description": "First reminder when a cart is abandoned.",
            "subject": "{brand} - your cart is waiting",
            "preheader": "You left a few items behind. Resume checkout anytime.",
            "title": "Your cart is waiting",
            "greeting": "Hi there,",
            "intro": "You left a few items in your cart. We saved them for you.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we will help.",
            "cta_label": "Resume checkout",
        },
        {
            "slug": "abandoned_cart_2",
            "name": "Abandoned cart (2nd)",
            "description": "Second reminder when a cart is abandoned.",
            "subject": "{brand} - still want these items?",
            "preheader": "Finish checkout whenever you are ready.",
            "title": "Your cart is still saved",
            "greeting": "Hi there,",
            "intro": "Your cart is still saved. If you want help with fitment or shipping, reply here.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we will help.",
            "cta_label": "Go to checkout",
        },
        {
            "slug": "abandoned_cart_3",
            "name": "Abandoned cart (3rd)",
            "description": "Final reminder when a cart is abandoned.",
            "subject": "{brand} - last reminder for your cart",
            "preheader": "Your cart is ready if you still want these items.",
            "title": "Last reminder for your cart",
            "greeting": "Hi there,",
            "intro": "Just a final reminder in case you still want these items.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we will help.",
            "cta_label": "Checkout now",
        },
        {
            "slug": "site_notice_welcome",
            "name": "Email signup: welcome code",
            "description": "Sent after someone joins the email list.",
            "subject": "{brand} welcome code",
            "preheader": "Welcome code inside: {welcome_code}",
            "title": "Your 5% welcome code",
            "greeting": "Thanks for joining the {brand} email list.",
            "intro": "Here is your welcome code for 5% off your first order.\nUse it on any product or service invoice.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we will help.",
            "cta_label": "Visit {brand}",
        },
        {
            "slug": "site_notice_followup_2",
            "name": "Email signup: 24h follow-up",
            "description": "Sent 24 hours after email signup.",
            "subject": "{brand} follow-up: your 5% code",
            "preheader": "Customer note + your 5% code: {welcome_code}",
            "title": "Your welcome code is still ready",
            "greeting": "Hi there,",
            "intro": "Your welcome code is still active: {welcome_code}.\nUse it on any product or service invoice.",
            "notice_title": "Customer note",
            "notice": "\"The install was clean and the team kept me updated the whole time.\"",
            "footer": "Questions? Reply to this email and we will help.",
            "cta_label": "Shop best sellers",
        },
        {
            "slug": "site_notice_followup_3",
            "name": "Email signup: 3-day follow-up",
            "description": "Sent 3 days after email signup.",
            "subject": "{brand} - want a quote or want to book in?",
            "preheader": "Ready when you are - book or browse services.",
            "title": "Want a quote or want to book in?",
            "greeting": "Hi there,",
            "intro": "We can price it out fast or lock in a time that works for you.\nPick a service or jump straight to booking.",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we will help.",
            "cta_label": "Book a service",
        },
        {
            "slug": "order_review_request",
            "name": "Order review request",
            "description": "Sent after completed orders to request a review.",
            "subject": "{brand} - how did we do?",
            "preheader": "A quick review helps the team a ton.",
            "title": "How did we do?",
            "greeting": "Hi {customer_name},",
            "intro": "Thanks again for your order.\nIf everything looks good, would you leave us a quick review?",
            "notice_title": "",
            "notice": "",
            "footer": "Questions? Reply to this email and we'll help.",
            "cta_label": "Leave a review",
        },
        {
            "slug": "fitment_request_internal",
            "name": "Custom fitment request (internal)",
            "description": "Internal alert when a custom fitment request is submitted.",
            "subject": "Custom fitment request — {product_name}",
            "preheader": "New request from {customer_name}",
            "title": "New custom fitment request",
            "greeting": "Team,",
            "intro": "A new custom fitment request just landed. Details below.",
            "notice_title": "Notes",
            "notice": "",
            "footer": "Reply to the customer within 1-2 business days.",
            "cta_label": "",
        },
    ]

    for payload in templates:
        EmailTemplate.objects.get_or_create(slug=payload["slug"], defaults=payload)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0052_homepagecopy_hero_logo_homepagecopy_hero_logo_alt_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "slug",
                    models.SlugField(
                        choices=[
                            ("appointment_confirmation", "Appointment confirmation"),
                            ("order_confirmation", "Order confirmation"),
                            ("order_status_processing", "Order status: processing"),
                            ("order_status_shipped", "Order status: shipped"),
                            ("order_status_completed", "Order status: completed"),
                            ("order_status_cancelled", "Order status: cancelled"),
                            ("abandoned_cart_1", "Abandoned cart (1st)"),
                            ("abandoned_cart_2", "Abandoned cart (2nd)"),
                            ("abandoned_cart_3", "Abandoned cart (3rd)"),
                            ("site_notice_welcome", "Email signup: welcome code"),
                            ("site_notice_followup_2", "Email signup: 24h follow-up"),
                            ("site_notice_followup_3", "Email signup: 3-day follow-up"),
                            ("order_review_request", "Order review request"),
                            ("fitment_request_internal", "Custom fitment request (internal)"),
                        ],
                        max_length=80,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("subject", models.CharField(max_length=180)),
                ("preheader", models.CharField(blank=True, max_length=180)),
                ("title", models.CharField(max_length=140)),
                ("greeting", models.CharField(blank=True, max_length=160)),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="One sentence per line. These lines appear near the top of the email.",
                    ),
                ),
                ("notice_title", models.CharField(blank=True, max_length=120)),
                (
                    "notice",
                    models.TextField(
                        blank=True,
                        help_text="Optional callout. One sentence per line.",
                    ),
                ),
                (
                    "footer",
                    models.TextField(
                        blank=True,
                        help_text="One sentence per line. Appears at the bottom of the email.",
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Email template",
                "verbose_name_plural": "Email templates",
                "ordering": ("name",),
            },
        ),
        migrations.RunPython(seed_email_templates, migrations.RunPython.noop),
    ]
