# Generated by Django 5.1.6 on 2026-01-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0053_admin_sidebar_seen"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="gallery_title",
            field=models.CharField(default="Project gallery", max_length=80),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="gallery_desc",
            field=models.TextField(default="Recent builds, wraps, and installs from the BGM shop floor."),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="gallery_cta_label",
            field=models.CharField(default="View photo gallery", max_length=60),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="gallery_cta_url",
            field=models.CharField(blank=True, default="/project-journal/", max_length=200),
        ),
        migrations.AlterField(
            model_name="heroimage",
            name="location",
            field=models.CharField(
                choices=[
                    ("home", "Home hero"),
                    ("home-gallery-a", "Home gallery — slot 1"),
                    ("home-gallery-b", "Home gallery — slot 2"),
                    ("home-gallery-c", "Home gallery — slot 3"),
                    ("home-gallery-d", "Home gallery — slot 4"),
                    ("dealer-status", "Dealer banner"),
                    ("store", "Store hero"),
                    ("merch", "Merch hero"),
                    ("brake-suspension-hero", "Brake & Suspension hero"),
                    ("brake-suspension-gallery-a", "Brake & Suspension gallery — top"),
                    ("brake-suspension-gallery-b", "Brake & Suspension gallery — middle"),
                    ("brake-suspension-gallery-c", "Brake & Suspension gallery — bottom"),
                    ("performance-tuning-hero", "Performance Tuning hero"),
                    ("performance-tuning-gallery-a", "Performance Tuning gallery — top"),
                    ("performance-tuning-gallery-b", "Performance Tuning gallery — middle"),
                    ("performance-tuning-gallery-c", "Performance Tuning gallery — bottom"),
                    ("electrical-work-hero", "Electrical Work hero"),
                    ("electrical-work-gallery-a", "Electrical Work gallery — top"),
                    ("electrical-work-gallery-b", "Electrical Work gallery — middle"),
                    ("electrical-work-gallery-c", "Electrical Work gallery — bottom"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Placement",
            ),
        ),
    ]
