# Generated by Codex on 2026-01-26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0055_merge_0054_home_gallery_section_0053_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_layout",
            field=models.CharField(
                choices=[("overlay", "Logo over photo"), ("stacked", "Logo then photo")],
                default="overlay",
                help_text="Controls whether the logo overlays the photo or the photo appears below it.",
                max_length=12,
            ),
        ),
    ]
