# Generated by Codex on 2026-01-26

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0056_homepagecopy_hero_logo_layout"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_bg_style",
            field=models.CharField(
                choices=[
                    ("dark", "Dark"),
                    ("light", "Light"),
                    ("accent", "Accent"),
                    ("transparent", "Transparent"),
                ],
                default="dark",
                help_text="Background style for the circular logo container.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_size",
            field=models.PositiveSmallIntegerField(
                default=180,
                help_text="Logo diameter in pixels (desktop).",
                validators=[
                    django.core.validators.MinValueValidator(96),
                    django.core.validators.MaxValueValidator(260),
                ],
            ),
        ),
    ]
