# Generated by Codex on 2026-01-27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0057_homepagecopy_hero_logo_bg_style_and_size"),
        ("core", "0057_merge_0056_homepagecopy_hero_logo_layout_0054_email_template_settings"),
    ]

    operations = []
