# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_merge_0057_homepagecopy_hero_logo_bg_style_and_size_0057_merge_0056_homepagecopy_hero_logo_layout_0054_email_template_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_media_width",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional hero image width (desktop px). Leave empty for auto.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_media_height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional hero image height (desktop px). Leave empty for auto.",
                null=True,
            ),
        ),
    ]
