# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0059_homepagecopy_hero_media_size"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_show_ring",
            field=models.BooleanField(
                default=True,
                help_text="Show circular ring around the hero logo.",
            ),
        ),
    ]
