# Generated by Codex on 2026-01-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0060_homepagecopy_hero_logo_show_ring"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_photo_width",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional width (px) for the photo under the logo (stacked layout only).",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_logo_photo_height",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="Optional height (px) for the photo under the logo (stacked layout only).",
                null=True,
            ),
        ),
    ]
