# Generated by Django 5.1.6 on 2026-01-28 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0061_homepagecopy_hero_logo_photo_size"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="adminsidebarseen",
            new_name="core_admins_user_id_31d4ba_idx",
            old_name="core_adminsi_user_model_idx",
        ),
    ]
