# Generated by Django 5.1.6 on 2026-01-29 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0063_clientuicheckrun"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailCampaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("partial", "Sent with errors"),
                            ("failed", "Failed"),
                        ],
                        default="draft",
                        max_length=12,
                    ),
                ),
                ("from_email", models.EmailField(blank=True, max_length=254)),
                ("subject", models.CharField(max_length=180)),
                ("preheader", models.CharField(blank=True, max_length=180)),
                ("title", models.CharField(max_length=140)),
                ("greeting", models.CharField(blank=True, max_length=160)),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="One sentence per line. These lines appear near the top of the email.",
                    ),
                ),
                ("notice_title", models.CharField(blank=True, max_length=120)),
                (
                    "notice",
                    models.TextField(
                        blank=True, help_text="Optional callout. One sentence per line."
                    ),
                ),
                (
                    "footer",
                    models.TextField(
                        blank=True,
                        help_text="One sentence per line. Appears at the bottom of the email.",
                    ),
                ),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_url", models.URLField(blank=True, max_length=500)),
                ("include_subscribers", models.BooleanField(default=True)),
                (
                    "include_registered_users",
                    models.BooleanField(
                        default=True,
                        help_text="Only users who opted into marketing emails are included.",
                    ),
                ),
                ("recipients_total", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("send_started_at", models.DateTimeField(blank=True, null=True)),
                ("send_completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_campaigns_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email campaign",
                "verbose_name_plural": "Email campaigns",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EmailCampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("subscriber", "Subscriber list"),
                            ("user", "Registered user"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("error_message", models.CharField(blank=True, max_length=255)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.emailcampaign",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_campaign_recipients",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email campaign recipient",
                "verbose_name_plural": "Email campaign recipients",
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="EmailSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("import", "Imported list"),
                            ("manual", "Manual entry"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="email_subscribers_added",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Email subscriber",
                "verbose_name_plural": "Email subscribers",
                "ordering": ("-created_at",),
            },
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(fields=["status"], name="core_emailc_status_d19fcc_idx"),
        ),
        migrations.AddIndex(
            model_name="emailcampaign",
            index=models.Index(
                fields=["created_at"], name="core_emailc_created_5004a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailcampaignrecipient",
            index=models.Index(
                fields=["campaign", "status"], name="core_emailc_campaig_0dd8ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailcampaignrecipient",
            index=models.Index(fields=["email"], name="core_emailc_email_c57c27_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="emailcampaignrecipient",
            unique_together={("campaign", "email")},
        ),
        migrations.AddIndex(
            model_name="emailsubscriber",
            index=models.Index(fields=["email"], name="core_emails_email_825009_idx"),
        ),
        migrations.AddIndex(
            model_name="emailsubscriber",
            index=models.Index(
                fields=["is_active"], name="core_emails_is_acti_463fb5_idx"
            ),
        ),
    ]
