# Generated by Django 5.1.6 on 2026-01-29 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0066_merge_0063_admin_login_branding_0065_userprofile_email_verification",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadSubmissionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("site_notice", "Site notice signup"),
                            ("service_lead", "Service lead"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("suspected", "Accepted (suspected)"),
                            ("blocked", "Blocked"),
                            ("rate_limited", "Rate limited"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                ("success", models.BooleanField(default=False)),
                ("suspicion_score", models.PositiveSmallIntegerField(default=0)),
                ("validation_errors", models.TextField(blank=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("accept_language", models.CharField(blank=True, max_length=512)),
                ("referer", models.CharField(blank=True, max_length=600)),
                ("origin", models.CharField(blank=True, max_length=300)),
                ("path", models.CharField(blank=True, max_length=300)),
                ("session_key_hash", models.CharField(blank=True, max_length=64)),
                ("session_first_seen_at", models.DateTimeField(blank=True, null=True)),
                ("time_on_page_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("cf_country", models.CharField(blank=True, max_length=12)),
                ("cf_asn", models.CharField(blank=True, max_length=40)),
                ("cf_asn_org", models.CharField(blank=True, max_length=200)),
                ("flags", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["form_type", "created_at"],
                        name="core_leadsu_form_ty_98c427_idx",
                    ),
                    models.Index(
                        fields=["outcome", "created_at"],
                        name="core_leadsu_outcome_7086a7_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="core_leadsu_ip_addr_f57085_idx",
                    ),
                ],
            },
        ),
    ]
