# Generated by Django 5.1.6 on 2026-01-29 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0067_leadsubmissionevent"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopbarSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "brand_size_desktop",
                    models.CharField(
                        default="clamp(1.25rem, 2.1vw, 1.7rem)",
                        help_text="CSS font-size value for the brand text (desktop).",
                        max_length=32,
                    ),
                ),
                (
                    "brand_weight",
                    models.CharField(
                        default="400",
                        help_text="CSS font-weight for the brand text.",
                        max_length=16,
                    ),
                ),
                (
                    "brand_letter_spacing",
                    models.CharField(
                        default="0",
                        help_text="CSS letter-spacing for the brand text.",
                        max_length=16,
                    ),
                ),
                (
                    "brand_transform",
                    models.CharField(
                        default="none",
                        help_text="CSS text-transform for the brand text.",
                        max_length=16,
                    ),
                ),
                (
                    "nav_size",
                    models.CharField(
                        default="0.95rem",
                        help_text="CSS font-size for nav links (mobile).",
                        max_length=16,
                    ),
                ),
                (
                    "nav_size_desktop",
                    models.CharField(
                        default="1.05rem",
                        help_text="CSS font-size for nav links (desktop).",
                        max_length=16,
                    ),
                ),
                (
                    "padding_y_desktop",
                    models.CharField(
                        default="0.95rem",
                        help_text="CSS padding-block for the top bar (desktop).",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "brand_font",
                    models.ForeignKey(
                        blank=True,
                        help_text="Font used for the business name in the top bar.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topbar_brand_settings",
                        to="core.fontpreset",
                    ),
                ),
                (
                    "nav_font",
                    models.ForeignKey(
                        blank=True,
                        help_text="Font used for navigation links and badges.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="topbar_nav_settings",
                        to="core.fontpreset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Topbar settings",
                "verbose_name_plural": "Topbar settings",
                "ordering": ("singleton_id",),
            },
        ),
    ]
