# Generated by Django 5.1.6 on 2026-01-29 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_topbarsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailtemplate",
            name="cta_url",
            field=models.CharField(
                blank=True,
                help_text="Optional button link override. Supports placeholders like {company_website}.",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="accent_color",
            field=models.CharField(
                blank=True,
                help_text="Optional override for EMAIL_ACCENT_COLOR (hex like #d50000).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="bg_color",
            field=models.CharField(
                blank=True,
                help_text="Optional override for EMAIL_BG_COLOR (hex like #0b0b0c).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="brand_tagline",
            field=models.CharField(
                blank=True,
                help_text="Optional override for SITE_BRAND_TAGLINE in email headers/footers.",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="company_address",
            field=models.CharField(
                blank=True,
                help_text="Optional override for COMPANY_ADDRESS in email footers.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="company_phone",
            field=models.CharField(
                blank=True,
                help_text="Optional override for COMPANY_PHONE in email footers.",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="company_website",
            field=models.CharField(
                blank=True,
                help_text="Optional override for COMPANY_WEBSITE in email footers and CTA defaults.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="dark_color",
            field=models.CharField(
                blank=True,
                help_text="Optional override for EMAIL_DARK_COLOR (hex like #0b0b0c).",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="support_email",
            field=models.EmailField(
                blank=True,
                help_text="Optional override for SUPPORT_EMAIL placeholders.",
                max_length=254,
            ),
        ),
    ]
