# Generated by Django 5.2.6 on 2026-01-29 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_emailtemplate_cta_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="heroimage",
            name="location",
            field=models.CharField(
                choices=[
                    ("home", "Home hero"),
                    ("home-carousel-a", "Home hero carousel — slide 1"),
                    ("home-carousel-b", "Home hero carousel — slide 2"),
                    ("home-carousel-c", "Home hero carousel — slide 3"),
                    ("home-carousel-d", "Home hero carousel — slide 4"),
                    ("home-gallery-a", "Home gallery — slot 1"),
                    ("home-gallery-b", "Home gallery — slot 2"),
                    ("home-gallery-c", "Home gallery — slot 3"),
                    ("home-gallery-d", "Home gallery — slot 4"),
                    ("dealer-status", "Dealer banner"),
                    ("store", "Store hero"),
                    ("merch", "Merch hero"),
                    ("brake-suspension-hero", "Brake & Suspension hero"),
                    ("brake-suspension-gallery-a", "Brake & Suspension gallery — top"),
                    (
                        "brake-suspension-gallery-b",
                        "Brake & Suspension gallery — middle",
                    ),
                    (
                        "brake-suspension-gallery-c",
                        "Brake & Suspension gallery — bottom",
                    ),
                    ("performance-tuning-hero", "Performance Tuning hero"),
                    ("performance-tuning-gallery-a", "Performance Tuning gallery — top"),
                    (
                        "performance-tuning-gallery-b",
                        "Performance Tuning gallery — middle",
                    ),
                    (
                        "performance-tuning-gallery-c",
                        "Performance Tuning gallery — bottom",
                    ),
                    ("electrical-work-hero", "Electrical Work hero"),
                    ("electrical-work-gallery-a", "Electrical Work gallery — top"),
                    ("electrical-work-gallery-b", "Electrical Work gallery — middle"),
                    ("electrical-work-gallery-c", "Electrical Work gallery — bottom"),
                ],
                max_length=32,
                unique=True,
                verbose_name="Placement",
            ),
        ),
    ]
