# Generated by Django 5.2.6 on 2026-01-30 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_heroimage_home_carousel"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="meta_title",
            field=models.CharField(
                default="BGM — Performance Builds & VIP Service",
                max_length=140,
            ),
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="meta_description",
            field=models.TextField(
                default=(
                    "Performance-driven builds, detailing, tuning, and a curated product catalog by BGM in Calgary."
                ),
            ),
        ),
    ]
