# Generated by Django 5.1.6 on 2026-01-30 20:51

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0071_homepagecopy_meta_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepagecopy",
            name="layout_overrides",
            field=models.JSONField(
                blank=True,
                default=core.models.default_home_layout_overrides,
                help_text="Manual layout offsets for hero elements (page builder).",
            ),
        ),
    ]
