# Generated by Django 5.1.6 on 2026-01-30 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0072_homepagecopy_layout_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackgroundAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=120)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        help_text="Upload a background image (webp/jpg recommended).",
                        null=True,
                        upload_to="backgrounds/",
                    ),
                ),
                (
                    "alt_text",
                    models.CharField(
                        blank=True,
                        help_text="Accessible description shown to screen readers.",
                        max_length=160,
                    ),
                ),
                (
                    "caption",
                    models.CharField(
                        blank=True,
                        help_text="Optional short line rendered under the hero image.",
                        max_length=160,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Background asset",
                "verbose_name_plural": "Background assets",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="hero_background_asset",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional background from the library (overrides the uploaded hero background).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_pages",
                to="core.backgroundasset",
            ),
        ),
        migrations.CreateModel(
            name="SiteBackgroundSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_background",
                    models.ForeignKey(
                        blank=True,
                        help_text="If set, overrides page-specific hero backgrounds across the site.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="site_defaults",
                        to="core.backgroundasset",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site background",
                "verbose_name_plural": "Site backgrounds",
                "ordering": ("singleton_id",),
            },
        ),
    ]
