# Generated by Django 5.2.4 on 2026-02-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("core", "0073_backgroundasset_homepagecopy_hero_background_asset_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageCopyDraft",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page copy draft",
                "verbose_name_plural": "Page copy drafts",
                "unique_together": {("content_type", "object_id")},
            },
        ),
        migrations.CreateModel(
            name="PageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero"),
                            ("text", "Text"),
                            ("image", "Image"),
                            ("gallery", "Gallery"),
                            ("faq", "FAQ"),
                            ("custom", "Custom HTML"),
                        ],
                        max_length=40,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "background_color",
                    models.CharField(
                        blank=True,
                        help_text="Optional CSS color (hex/rgb) for the section background.",
                        max_length=32,
                    ),
                ),
                (
                    "overlay_color",
                    models.CharField(
                        blank=True,
                        help_text="Optional overlay color applied on top of background image.",
                        max_length=32,
                    ),
                ),
                (
                    "layout_overrides",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Manual layout overrides for section elements.",
                    ),
                ),
                ("is_hidden", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "background_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_sections",
                        to="core.backgroundasset",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Page section",
                "verbose_name_plural": "Page sections",
                "ordering": ("order", "id"),
            },
        ),
        migrations.AddField(
            model_name="homepagecopy",
            name="default_background",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional default background for the home page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="home_default_backgrounds",
                to="core.backgroundasset",
            ),
        ),
        migrations.AddField(
            model_name="servicespagecopy",
            name="default_background",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional default background for the services page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services_default_backgrounds",
                to="core.backgroundasset",
            ),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="default_background",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional default background for the store page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_default_backgrounds",
                to="core.backgroundasset",
            ),
        ),
    ]
