# Generated by Codex on 2026-02-01
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0074_page_sections_and_drafts"),
    ]

    operations = [
        migrations.AddField(
            model_name="pagefontsetting",
            name="style_overrides",
            field=models.JSONField(blank=True, default=dict, help_text="Optional per-page typography overrides (size, weight, spacing)."),
        ),
    ]
