# Generated by Django 5.1.6 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0077_about_story_photo_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="merchpagecopy",
            name="coming_soon_badge",
            field=models.CharField(default="Coming soon", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="coming_soon_desc",
            field=models.CharField(
                default="We’re finalizing samples, colours, and sizing. Join the drop list for first access.",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="coming_soon_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="coming_soon_title",
            field=models.CharField(default="Merch drop incoming", max_length=120),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_1_colors",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_1_photo",
            field=models.ImageField(blank=True, null=True, upload_to="merch/cards/"),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_1_photo_alt",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_1_sizes",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_2_colors",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_2_photo",
            field=models.ImageField(blank=True, null=True, upload_to="merch/cards/"),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_2_photo_alt",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_2_sizes",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_3_colors",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_3_photo",
            field=models.ImageField(blank=True, null=True, upload_to="merch/cards/"),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_3_photo_alt",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_3_sizes",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_4_colors",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_4_photo",
            field=models.ImageField(blank=True, null=True, upload_to="merch/cards/"),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_4_photo_alt",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_4_sizes",
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_colors_label",
            field=models.CharField(default="Colours", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="card_sizes_label",
            field=models.CharField(default="Sizes", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="contact_email",
            field=models.EmailField(default="support@badguymotors.com", max_length=254),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="contact_email_subject",
            field=models.CharField(default="Inquiry from website", max_length=120),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="contact_phone",
            field=models.CharField(default="+14035250432", max_length=32),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="contact_phone_display",
            field=models.CharField(default="(403) 525-0432", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_1_label",
            field=models.CharField(default="Instagram", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_1_url",
            field=models.URLField(
                blank=True,
                default="https://www.instagram.com/badguymotors?igsh=N2QwZnVybTJrZW8=",
            ),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_2_label",
            field=models.CharField(default="Facebook", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_2_url",
            field=models.URLField(
                blank=True,
                default="https://www.facebook.com/share/1Gsej2u5X4/?mibextid=wwXIfr",
            ),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_3_label",
            field=models.CharField(default="YouTube", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_3_url",
            field=models.URLField(
                blank=True,
                default="https://youtube.com/@badguymotors?si=PObKEe6vNMEr3Z2b",
            ),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_4_label",
            field=models.CharField(default="TikTok", max_length=40),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_link_4_url",
            field=models.URLField(
                blank=True,
                default="https://www.tiktok.com/@savoies0?_r=1&_t=ZS-93JwAHrfF5k",
            ),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_section_desc",
            field=models.CharField(
                default="Behind-the-scenes, restocks, and first access alerts.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="merchpagecopy",
            name="social_section_title",
            field=models.CharField(default="Follow the drop", max_length=80),
        ),
    ]
