# Generated by Django 5.1.6 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0078_merch_content_support"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectjournalentry",
            name="backstory",
            field=models.TextField(
                blank=True,
                help_text="Narrative backstory for the build.",
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="customizations",
            field=models.TextField(
                blank=True,
                help_text="Custom fabrication, tuning, or unique upgrades (one per line).",
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="overview",
            field=models.TextField(
                blank=True,
                help_text="High-level summary for the gallery overview panel.",
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="parts",
            field=models.TextField(
                blank=True,
                help_text="Parts list or components used (one per line).",
            ),
        ),
    ]
