# Generated by Django 5.1.6 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0079_project_journal_gallery_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_desc",
            field=models.CharField(
                default="Two liner finishes, two personalities. Compare the feel before you book.",
                max_length=160,
            ),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_left_body",
            field=models.TextField(
                default="Thick, textured finish built for abuse.\nIdeal for heavy-use beds and work rigs.\nMaximum grip and impact resistance.",
            ),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_left_subtitle",
            field=models.CharField(default="Textured, rugged liner", max_length=80),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_left_title",
            field=models.CharField(default="Armadillo", max_length=60),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_right_body",
            field=models.TextField(
                default="Smoother finish with a show-ready look.\nEasy to clean with a sleek feel.\nGreat for street builds and interiors.",
            ),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_right_subtitle",
            field=models.CharField(default="Smooth Criminal Liner", max_length=80),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_right_title",
            field=models.CharField(default="SCL", max_length=60),
        ),
        migrations.AddField(
            model_name="storepagecopy",
            name="comparison_title",
            field=models.CharField(default="Armadillo vs SCL", max_length=80),
        ),
    ]
