# Generated by Django 5.1.6 on 2026-02-03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0080_store_comparison_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSendLog",
            fields=[
                ("id", models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, serialize=False)),
                ("email_type", models.CharField(max_length=120, db_index=True)),
                ("subject", models.CharField(max_length=200, blank=True)),
                ("from_email", models.EmailField(max_length=254, blank=True)),
                ("recipients", models.JSONField(default=list, blank=True)),
                ("recipient_count", models.PositiveIntegerField(default=0)),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Email send log",
                "verbose_name_plural": "Email send logs",
                "ordering": ("-sent_at",),
            },
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(fields=["email_type"], name="core_email__email_t_5f46d2_idx"),
        ),
        migrations.AddIndex(
            model_name="emailsendlog",
            index=models.Index(fields=["sent_at"], name="core_email__sent_a_7e1b01_idx"),
        ),
    ]
