# Generated by Django 5.1.6 on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0081_email_send_log"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="notify_on_fitment_request",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="notify_on_new_appointment",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="notify_on_new_order",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="notify_on_order_review_request",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="notify_on_service_lead",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="role",
            name="notify_on_site_notice_signup",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_product_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="email_service_updates",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clientportalpagecopy",
            name="profile_email_marketing_label",
            field=models.CharField(default="News & offers", max_length=120),
        ),
        migrations.AddField(
            model_name="clientportalpagecopy",
            name="profile_email_prefs_title",
            field=models.CharField(default="Email preferences", max_length=80),
        ),
        migrations.AddField(
            model_name="clientportalpagecopy",
            name="profile_email_product_label",
            field=models.CharField(default="Product drops & merch alerts", max_length=120),
        ),
        migrations.AddField(
            model_name="clientportalpagecopy",
            name="profile_email_service_label",
            field=models.CharField(default="Build updates & service reminders", max_length=120),
        ),
    ]
