# Generated by Django 5.1.6 on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0084_topbar_word_style_controls"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectjournalentry",
            name="after_gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of after photos as JSON (e.g. [{\"url\":\"...\",\"alt\":\"...\"}] or [\"url1\",\"url2\"]).",
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="before_gallery",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of before photos as JSON (e.g. [{\"url\":\"...\",\"alt\":\"...\"}] or [\"url1\",\"url2\"]).",
            ),
        ),
    ]
