# Generated by Django 5.1.6 on 2026-02-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0085_project_journal_before_after_gallery"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectJournalPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("before", "Before"), ("after", "After")], max_length=10)),
                ("image", models.ImageField(upload_to="project-journal/photos/")),
                ("alt_text", models.CharField(blank=True, max_length=140)),
                ("sort_order", models.PositiveSmallIntegerField(default=0, help_text="Lower numbers show first.")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("entry", models.ForeignKey(on_delete=models.deletion.CASCADE, related_name="photos", to="core.projectjournalentry")),
            ],
            options={
                "verbose_name": "Project journal photo",
                "verbose_name_plural": "Project journal photos",
                "ordering": ("sort_order", "created_at"),
            },
        ),
    ]
