# Generated by Django 5.2.4 on 2026-02-05 21:57

from django.db import migrations, models


def populate_rates_policies(apps, schema_editor):
    AboutPageCopy = apps.get_model("core", "AboutPageCopy")
    for obj in AboutPageCopy.objects.all():
        lines = [obj.rates_policy_1, obj.rates_policy_2, obj.rates_policy_3]
        text = "\n".join([line.strip() for line in lines if line and line.strip()])
        obj.rates_policies = text
        obj.save(update_fields=["rates_policies"])


def reverse_rates_policies(apps, schema_editor):
    AboutPageCopy = apps.get_model("core", "AboutPageCopy")
    for obj in AboutPageCopy.objects.all():
        if not obj.rates_policies:
            obj.rates_policy_1 = ""
            obj.rates_policy_2 = ""
            obj.rates_policy_3 = ""
        else:
            lines = [line.strip() for line in obj.rates_policies.splitlines() if line.strip()]
            obj.rates_policy_1 = lines[0] if len(lines) > 0 else ""
            obj.rates_policy_2 = lines[1] if len(lines) > 1 else ""
            obj.rates_policy_3 = lines[2] if len(lines) > 2 else ""
        obj.save(update_fields=["rates_policy_1", "rates_policy_2", "rates_policy_3"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_topbar_tagline_words"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagecopy",
            name="rates_policies",
            field=models.TextField(
                default=(
                    "Deposits secure your slot; balance due on delivery.\n"
                    "Storage fees may apply for completed items not picked up promptly.\n"
                    "Warranty & support — if it isn’t right, we make it right."
                ),
                help_text="One policy per line.",
            ),
        ),
        migrations.RunPython(populate_rates_policies, reverse_rates_policies),
    ]
