# Generated by Django 5.2.4 on 2026-02-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0090_aboutpage_rates_policies_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientportalpagecopy",
            name="rates_customer_parts_label",
            field=models.CharField(default="Customer supplied parts", max_length=80),
        ),
        migrations.AddField(
            model_name="clientportalpagecopy",
            name="rates_customer_parts_value",
            field=models.CharField(default="145/hr", max_length=40),
        ),
    ]

