# Generated by Django 5.2.4 on 2026-02-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0091_clientportal_rates_customer_supplied_parts"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagecopy",
            name="rates_customer_parts_label",
            field=models.CharField(default="Customer supplied parts", max_length=80),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="rates_customer_parts_value",
            field=models.CharField(default="145/hr", max_length=40),
        ),
    ]

