# Generated by Django 5.2.4 on 2026-02-07

from django.db import migrations, models
import django.db.models.deletion


def seed_homepage_faq_items(apps, schema_editor):
    HomePageCopy = apps.get_model("core", "HomePageCopy")
    HomePageFAQItem = apps.get_model("core", "HomePageFAQItem")

    home_copy, _ = HomePageCopy.objects.get_or_create(singleton_id=1)
    if HomePageFAQItem.objects.filter(home_page_copy=home_copy).exists():
        return

    items = []
    for idx in range(1, 4):
        question = getattr(home_copy, f"faq_{idx}_question", "") or ""
        answer = getattr(home_copy, f"faq_{idx}_answer", "") or ""
        if not (question.strip() or answer.strip()):
            continue
        items.append(
            HomePageFAQItem(
                home_page_copy=home_copy,
                order=idx,
                question=question.strip(),
                answer=answer.strip(),
                is_published=True,
            )
        )
    if items:
        HomePageFAQItem.objects.bulk_create(items)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0092_aboutpage_customer_supplied_parts_rate"),
    ]

    operations = [
        migrations.CreateModel(
            name="HomePageFAQItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("question", models.CharField(max_length=160)),
                ("answer", models.TextField()),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="If unchecked, this FAQ is saved as a draft and will not be shown on the website.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "home_page_copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_items",
                        to="core.homepagecopy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Home page FAQ",
                "verbose_name_plural": "Home page FAQs",
                "ordering": ("order", "id"),
            },
        ),
        migrations.RunPython(seed_homepage_faq_items, migrations.RunPython.noop),
    ]

