# Generated by Django 5.2.4 on 2026-02-10 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0093_home_page_faq_items"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="emailsendlog",
            new_name="core_emails_email_t_ba86a4_idx",
            old_name="core_email__email_t_5f46d2_idx",
        ),
        migrations.RenameIndex(
            model_name="emailsendlog",
            new_name="core_emails_sent_at_79c55c_idx",
            old_name="core_email__sent_a_7e1b01_idx",
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="brand_logo",
            field=models.ImageField(
                blank=True,
                help_text="Optional logo shown next to the brand name in email headers.",
                null=True,
                upload_to="email/branding/",
            ),
        ),
        migrations.AddField(
            model_name="emailtemplatesettings",
            name="brand_logo_alt",
            field=models.CharField(
                blank=True,
                help_text="Alt text for the email logo image. Leave blank to use the brand name.",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="landingpagereview",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home page"),
                    ("performance_tuning", "Performance tuning"),
                    ("electrical_work", "Electrical work"),
                    ("brake_suspension", "Brake & suspension"),
                ],
                db_index=True,
                help_text="Landing page that will display this review.",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="pagefontsetting",
            name="page",
            field=models.CharField(
                choices=[
                    ("home", "Home page"),
                    ("services", "Services page"),
                    ("store", "Store page"),
                    ("merch", "Merch page"),
                    ("financing", "Financing page"),
                    ("about", "About page"),
                    ("brake_suspension", "Brake & Suspension page"),
                    ("wheel_tire_service", "Wheel & Tire Service page"),
                    ("performance_tuning", "Performance Tuning page"),
                    ("electrical_work", "Electrical Work page"),
                    ("project_journal", "Project journal"),
                ],
                help_text="Page that will consume the configured fonts.",
                max_length=80,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="topbarsettings",
            name="brand_word_red_font",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional font override for the third brand word.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topbar_brand_word_red_settings",
                to="core.fontpreset",
            ),
        ),
    ]
