# Generated by Django 5.2.4 on 2026-02-11 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "core",
            "0094_rename_core_email__email_t_5f46d2_idx_core_emails_email_t_ba86a4_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectJournalCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=90, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Lower numbers show first in filters."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Project journal category",
                "verbose_name_plural": "Project journal categories",
                "ordering": ("sort_order", "name"),
            },
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="cta_primary_label",
            field=models.CharField(
                blank=True,
                help_text="Primary button label (e.g. Book now).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="cta_primary_url",
            field=models.CharField(
                blank=True,
                help_text="Primary button link (absolute or relative URL).",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="cta_secondary_label",
            field=models.CharField(
                blank=True,
                help_text="Secondary button label (e.g. Get quote).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="cta_secondary_url",
            field=models.CharField(
                blank=True,
                help_text="Secondary button link (absolute or relative URL).",
                max_length=240,
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="cta_tertiary_label",
            field=models.CharField(
                blank=True,
                help_text="Optional third button label (e.g. Explore services).",
                max_length=64,
            ),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="cta_tertiary_url",
            field=models.CharField(
                blank=True,
                help_text="Optional third button link (absolute or relative URL).",
                max_length=240,
            ),
        ),
        migrations.AlterField(
            model_name="projectjournalentry",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Used for fast public filters (curated, multi-select).",
                related_name="entries",
                to="core.projectjournalcategory",
            ),
        ),
    ]
