# Generated by Codex on 2026-02-11

from django.db import migrations


def seed_categories_from_tags(apps, schema_editor):
    Entry = apps.get_model("core", "ProjectJournalEntry")
    Category = apps.get_model("core", "ProjectJournalCategory")

    try:
        from django.utils.text import slugify
    except Exception:
        slugify = None

    def _slug(value: str) -> str:
        value = (value or "").strip()
        if not value:
            return ""
        if slugify:
            return slugify(value)[:90]
        return value.lower().replace(" ", "-")[:90]

    # Build existing slug set so we can keep slugs unique.
    existing_slugs = set(Category.objects.values_list("slug", flat=True))
    key_to_category_id = {}

    for entry in Entry.objects.all().only("id", "tags"):
        raw = (getattr(entry, "tags", "") or "").strip()
        if not raw:
            continue
        tags = [seg.strip() for seg in raw.split(",") if seg.strip()]
        if not tags:
            continue

        for tag in tags:
            name_base = tag.replace("_", " ").replace("-", " ").strip()
            key = name_base.lower() or tag.lower()
            cat_id = key_to_category_id.get(key)
            if cat_id is None:
                name = name_base or tag.replace("_", " ").strip()
                if name.islower():
                    name = name.title()

                slug_base = _slug(name) or _slug(tag)
                slug_value = slug_base or "category"
                suffix = 2
                while slug_value in existing_slugs:
                    slug_value = f"{slug_base}-{suffix}" if slug_base else f"category-{suffix}"
                    slug_value = slug_value[:90]
                    suffix += 1

                cat = Category.objects.create(
                    name=name[:80] or tag[:80] or "Category",
                    slug=slug_value,
                    is_active=True,
                    sort_order=0,
                )
                existing_slugs.add(slug_value)
                cat_id = cat.id
                key_to_category_id[key] = cat_id

            # ManyToMany add using historical relation.
            entry.categories.add(cat_id)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0095_projectjournalcategory_and_more"),
    ]

    operations = [
        migrations.RunPython(seed_categories_from_tags, reverse_code=migrations.RunPython.noop),
    ]
