# Generated by Django 5.2.4 on 2026-02-11 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0096_seed_project_journal_categories_from_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectJournalAfterPhoto",
            fields=[],
            options={
                "verbose_name": "After photo",
                "verbose_name_plural": "After photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.projectjournalphoto",),
        ),
        migrations.CreateModel(
            name="ProjectJournalBeforePhoto",
            fields=[],
            options={
                "verbose_name": "Before photo",
                "verbose_name_plural": "Before photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.projectjournalphoto",),
        ),
    ]
