# Generated by Django 5.2.4 on 2026-02-12 04:34

import django.db.models.deletion
from django.db import migrations, models


def seed_legacy_merch_cards(apps, schema_editor):
    MerchPageCopy = apps.get_model("core", "MerchPageCopy")
    MerchGalleryItem = apps.get_model("core", "MerchGalleryItem")

    for merch_page in MerchPageCopy.objects.all():
        for idx in range(1, 5):
            title = (getattr(merch_page, f"card_{idx}_title", "") or "").strip()
            description = (getattr(merch_page, f"card_{idx}_desc", "") or "").strip()
            photo = getattr(merch_page, f"card_{idx}_photo", None)
            photo_alt = (getattr(merch_page, f"card_{idx}_photo_alt", "") or "").strip()
            colors = (getattr(merch_page, f"card_{idx}_colors", "") or "").strip()
            sizes = (getattr(merch_page, f"card_{idx}_sizes", "") or "").strip()

            if not photo:
                continue

            card_title = title or f"Item {idx}"
            sort_order = idx * 10
            if MerchGalleryItem.objects.filter(
                merch_page_id=merch_page.pk,
                title=card_title,
                sort_order=sort_order,
            ).exists():
                continue

            MerchGalleryItem.objects.create(
                merch_page_id=merch_page.pk,
                category="Featured",
                title=card_title,
                description=description,
                photo=photo,
                photo_alt=photo_alt,
                colors=colors,
                sizes=sizes,
                sort_order=sort_order,
                is_active=True,
            )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0097_projectjournalafterphoto_projectjournalbeforephoto"),
    ]

    operations = [
        migrations.CreateModel(
            name="MerchGalleryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="Featured",
                        help_text="Cards are grouped by this label on the merch page (e.g. Apparel, Headwear, Accessories).",
                        max_length=80,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Short card title shown under the image.",
                        max_length=80,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=180)),
                ("photo", models.ImageField(upload_to="merch/gallery/")),
                ("photo_alt", models.CharField(blank=True, max_length=160)),
                ("colors", models.CharField(blank=True, max_length=160)),
                ("sizes", models.CharField(blank=True, max_length=160)),
                (
                    "sort_order",
                    models.PositiveIntegerField(
                        default=10, help_text="Lower numbers appear first."
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "merch_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery_items",
                        to="core.merchpagecopy",
                    ),
                ),
            ],
            options={
                "verbose_name": "Merch gallery item",
                "verbose_name_plural": "Merch gallery items",
                "ordering": ("sort_order", "id"),
            },
        ),
        migrations.RunPython(seed_legacy_merch_cards, migrations.RunPython.noop),
    ]
