# Generated by Django 5.2.4 on 2026-02-12 05:22

import django.core.validators
from django.db import migrations, models


def seed_project_journal_copy(apps, schema_editor):
    ProjectJournalPageCopy = apps.get_model("core", "ProjectJournalPageCopy")
    ProjectJournalPageCopy.objects.get_or_create(singleton_id=1)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0098_merchgalleryitem"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectJournalPageCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                ("page_title", models.CharField(default="Builds", max_length=160)),
                (
                    "meta_description",
                    models.TextField(
                        default="Before-and-after build highlights from Bad Guy Motors. Fast scans, clean comparisons, zero fluff."
                    ),
                ),
                (
                    "hero_eyebrow",
                    models.CharField(default="Builds / Gallery", max_length=80),
                ),
                (
                    "hero_lead",
                    models.TextField(
                        default="One-post-per-screen highlights: compare before/after first, then open details only if you want the full story."
                    ),
                ),
                (
                    "search_placeholder",
                    models.CharField(
                        default="Search builds (title, tags, notes)", max_length=120
                    ),
                ),
                (
                    "sort_featured_label",
                    models.CharField(default="Featured", max_length=40),
                ),
                (
                    "sort_newest_label",
                    models.CharField(default="Newest", max_length=40),
                ),
                (
                    "apply_filters_label",
                    models.CharField(default="Apply", max_length=40),
                ),
                (
                    "clear_filters_label",
                    models.CharField(default="Clear", max_length=40),
                ),
                (
                    "empty_results_label",
                    models.CharField(
                        default="No builds found. Try clearing filters or searching by a different keyword.",
                        max_length=180,
                    ),
                ),
                (
                    "filters_min_build_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Filters/search are shown when published build count reaches this number. They still appear when a filter is already active.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(999),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Project journal copy",
                "verbose_name_plural": "Project journal copy",
                "ordering": ("singleton_id",),
            },
        ),
        migrations.RunPython(seed_project_journal_copy, migrations.RunPython.noop),
    ]
