# Generated by Django 5.2.4 on 2026-02-12 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_projectjournalpagecopy"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealerapplication",
            name="authorized_signature_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Authorized signature date"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="authorized_signature_printed_name",
            field=models.CharField(
                blank=True,
                max_length=160,
                verbose_name="Authorized signature printed name",
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="authorized_signature_title",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Authorized signature title"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="business_address",
            field=models.TextField(blank=True, verbose_name="Business address"),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="business_license_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Business License #"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="business_type",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Type of business"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="city",
            field=models.CharField(blank=True, max_length=80, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254, verbose_name="Email"),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="gst_tax_id",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="GST / Tax ID"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="operating_as",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Operating as"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=20, verbose_name="Postal / ZIP code"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="province",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="Province / State"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="reference_1_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Reference 1 email"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="reference_1_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Reference 1 name"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="reference_1_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Reference 1 phone"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="reference_2_email",
            field=models.EmailField(
                blank=True, max_length=254, verbose_name="Reference 2 email"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="reference_2_name",
            field=models.CharField(
                blank=True, max_length=120, verbose_name="Reference 2 name"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="reference_2_phone",
            field=models.CharField(
                blank=True, max_length=32, verbose_name="Reference 2 phone"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="resale_certificate_number",
            field=models.CharField(
                blank=True, max_length=64, verbose_name="Resale Certificate #"
            ),
        ),
        migrations.AddField(
            model_name="dealerapplication",
            name="years_in_business",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="Years in business"
            ),
        ),
    ]
