# Generated by Django 5.2.4 on 2026-02-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_email_templates_no_reply"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectJournalProcessPhoto",
            fields=[],
            options={
                "verbose_name": "Process photo",
                "verbose_name_plural": "Process photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("core.projectjournalphoto",),
        ),
        migrations.AddField(
            model_name="projectjournalentry",
            name="desktop_media_mode",
            field=models.CharField(
                choices=[
                    ("slider", "Desktop: Drag before/after"),
                    ("album", "Desktop: Statement photo + click-through album"),
                ],
                default="slider",
                help_text="Desktop only. Mobile keeps the current compare layout.",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="projectjournalphoto",
            name="kind",
            field=models.CharField(
                choices=[
                    ("before", "Before"),
                    ("process", "Process"),
                    ("after", "After"),
                ],
                max_length=10,
            ),
        ),
    ]
