# Generated by Django 5.2.4 on 2026-02-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0105_storepagecopy_fitment_success_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emailtemplate",
            name="slug",
            field=models.SlugField(
                choices=[
                    ("appointment_confirmation", "Appointment confirmation"),
                    ("order_confirmation", "Order confirmation"),
                    ("order_status_processing", "Order status: processing"),
                    ("order_status_shipped", "Order status: shipped"),
                    ("order_status_completed", "Order status: completed"),
                    ("order_status_cancelled", "Order status: cancelled"),
                    ("abandoned_cart_1", "Abandoned cart (1st)"),
                    ("abandoned_cart_2", "Abandoned cart (2nd)"),
                    ("abandoned_cart_3", "Abandoned cart (3rd)"),
                    ("site_notice_welcome", "Email signup: welcome code"),
                    ("site_notice_followup_2", "Email signup: 24h follow-up"),
                    ("site_notice_followup_3", "Email signup: 3-day follow-up"),
                    ("order_review_request", "Order review request"),
                    ("fitment_request_internal", "Custom fitment request (internal)"),
                    ("dealer_application_submitted", "Dealer application: submitted"),
                    ("dealer_application_approved", "Dealer application: approved"),
                    ("dealer_application_rejected", "Dealer application: declined"),
                ],
                max_length=80,
                unique=True,
            ),
        ),
    ]
