# Generated by Django 5.2.4 on 2026-02-13 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0106_alter_emailtemplate_slug"),
        ("store", "0027_store_review"),
    ]

    operations = [
        # IMPORTANT: The legacy core_clientreview table already exists in production.
        # We only want to rename the *model* in Django state, not rename the DB table.
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameModel(
                    old_name="ClientReview",
                    new_name="AppointmentReview",
                ),
                migrations.AlterModelOptions(
                    name="appointmentreview",
                    options={
                        "verbose_name": "Appointment review",
                        "verbose_name_plural": "Appointment reviews",
                    },
                ),
                migrations.AlterModelTable(
                    name="appointmentreview",
                    table="core_clientreview",
                ),
            ],
        ),
        # Proxy the real public review model (store.StoreReview) so moderation happens at:
        # /admin/core/clientreview/
        migrations.CreateModel(
            name="ClientReview",
            fields=[],
            options={
                "verbose_name": "Client review",
                "verbose_name_plural": "Client reviews",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("store.storereview",),
        ),
    ]
