# Generated by Django 5.2.4 on 2026-02-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0107_rename_clientreview_appointmentreview_clientreview_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerapplication",
            name="assigned_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Tier 1"),
                    ("TIER_10", "Tier 2"),
                    ("TIER_15", "Tier 3"),
                ],
                help_text="Tier granted by the admin team when approving the account.",
                max_length=16,
                verbose_name="Assigned tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealerapplication",
            name="preferred_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Tier 1"),
                    ("TIER_10", "Tier 2"),
                    ("TIER_15", "Tier 3"),
                ],
                default="TIER_5",
                help_text="Requested tier based on projected volume.",
                max_length=16,
                verbose_name="Preferred tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealertierlevel",
            name="code",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Tier 1"),
                    ("TIER_10", "Tier 2"),
                    ("TIER_15", "Tier 3"),
                ],
                max_length=16,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dealer_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "Tier 1"),
                    ("TIER_10", "Tier 2"),
                    ("TIER_15", "Tier 3"),
                ],
                default="NONE",
                max_length=16,
                verbose_name="Dealer tier",
            ),
        ),
    ]
