# Generated by Django 5.2.4 on 2026-02-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0108_alter_dealerapplication_assigned_tier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="role",
            name="admin_sidebar_visible_groups",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Optional: limit which admin sidebar sections are visible for this role. Leave empty to show everything.",
            ),
        ),
    ]
