# Generated by Django 5.2.4 on 2026-02-14 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0109_role_admin_sidebar_visible_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_10",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_11",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_12",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_13",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_14",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_15",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_16",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
        migrations.AddField(
            model_name="aboutpagecopy",
            name="build_item_9",
            field=models.CharField(blank=True, default="", max_length=140),
        ),
    ]
