# Generated by Django 5.2.4 on 2026-02-14 23:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0110_aboutpagecopy_build_item_10_and_more"),
        ("store", "0030_merchcategory_product_merch_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointmentpromocode",
            name="discount_applied",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Discount amount applied to the appointment.",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="applicable_products",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all products.",
                to="store.product",
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="applies_to_products",
            field=models.BooleanField(
                default=False, help_text="Enable this promo code for store products."
            ),
        ),
        migrations.AddField(
            model_name="promocode",
            name="applies_to_services",
            field=models.BooleanField(
                default=True, help_text="Enable this promo code for service bookings."
            ),
        ),
        migrations.AddField(
            model_name="servicespagecopy",
            name="booking_promocode_label",
            field=models.CharField(default="Promo code (optional)", max_length=60),
        ),
        migrations.AddField(
            model_name="servicespagecopy",
            name="booking_promocode_placeholder",
            field=models.CharField(default="Enter code", max_length=120),
        ),
        migrations.AlterField(
            model_name="promocode",
            name="applicable_services",
            field=models.ManyToManyField(
                blank=True,
                help_text="Leave empty to apply to all services.",
                to="core.service",
            ),
        ),
    ]
