# Generated by Codex on 2026-02-22

from django.db import migrations, models


def update_financing_copy(apps, schema_editor):
    FinancingPageCopy = apps.get_model("core", "FinancingPageCopy")
    obj, _ = FinancingPageCopy.objects.get_or_create(singleton_id=1)
    obj.meta_description = (
        "Flexible financing partners for builds, parts, and installs including AutoLogiQ and Afterpay."
    )
    obj.provider_1_title = "AutoLogiQ"
    obj.provider_1_meta = "Credit-based or vehicle-based • Up to $12,500"
    obj.provider_1_desc = (
        "Existing estimate required to apply. Credit-based or vehicle-based financing available up to $12,500. "
        "Vehicles older than 10 years: financing limited."
    )
    obj.provider_1_primary_cta_label = "Apply with AutoLogiQ"
    obj.step_2_desc = "Use AutoLogiQ for larger projects, or Afterpay for smaller purchases."
    obj.faq_1_title = "Credit-based loans"
    obj.faq_1_desc = (
        "The Max Credit Limit and Estimated Payment shown are for illustration only and are based on a 13.99% "
        "interest rate (lowest applicable rate for 24- and 36-month terms). The final loan amount, term, interest "
        "rate, and payment are determined by the funder after a credit check and final approval. If the client does "
        "not qualify or opts out of a credit-based loan, the vehicle may still qualify for a loan based on its value. "
        "More information is available on the EasyPay FAQ page."
    )
    obj.faq_2_title = "Vehicle-based loans"
    obj.faq_2_desc = (
        "No credit check is required for loans secured by the vehicle's value in provinces where this type of loan is "
        "offered. The Maximum Credit Limit is calculated as a percentage of the vehicle's current Black Book value. "
        "Estimated payment is based on a 24.99% interest rate for a 36-month term. All loans, including those subject "
        "to a personal credit check, are subject to final approval upon receipt and review of the completed loan "
        "application."
    )
    obj.save(update_fields=[
        "meta_description",
        "provider_1_title",
        "provider_1_meta",
        "provider_1_desc",
        "provider_1_primary_cta_label",
        "step_2_desc",
        "faq_1_title",
        "faq_1_desc",
        "faq_2_title",
        "faq_2_desc",
        "updated_at",
    ])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0111_appointmentpromocode_discount_applied_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="financingpagecopy",
            name="meta_description",
            field=models.TextField(
                default=(
                    "Flexible financing partners for builds, parts, and installs including AutoLogiQ and Afterpay."
                )
            ),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="provider_1_title",
            field=models.CharField(default="AutoLogiQ", max_length=80),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="provider_1_meta",
            field=models.CharField(
                default="Credit-based or vehicle-based • Up to $12,500", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="provider_1_desc",
            field=models.TextField(
                default=(
                    "Existing estimate required to apply. Credit-based or vehicle-based financing available up to "
                    "$12,500. Vehicles older than 10 years: financing limited."
                )
            ),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="provider_1_primary_cta_label",
            field=models.CharField(default="Apply with AutoLogiQ", max_length=80),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="step_2_desc",
            field=models.TextField(
                default="Use AutoLogiQ for larger projects, or Afterpay for smaller purchases."
            ),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="faq_1_title",
            field=models.CharField(default="Credit-based loans", max_length=80),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="faq_1_desc",
            field=models.TextField(
                default=(
                    "The Max Credit Limit and Estimated Payment shown are for illustration only and are based on a "
                    "13.99% interest rate (lowest applicable rate for 24- and 36-month terms). The final loan amount, "
                    "term, interest rate, and payment are determined by the funder after a credit check and final "
                    "approval. If the client does not qualify or opts out of a credit-based loan, the vehicle may still "
                    "qualify for a loan based on its value. More information is available on the EasyPay FAQ page."
                )
            ),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="faq_2_title",
            field=models.CharField(default="Vehicle-based loans", max_length=80),
        ),
        migrations.AlterField(
            model_name="financingpagecopy",
            name="faq_2_desc",
            field=models.TextField(
                default=(
                    "No credit check is required for loans secured by the vehicle's value in provinces where this type "
                    "of loan is offered. The Maximum Credit Limit is calculated as a percentage of the vehicle's "
                    "current Black Book value. Estimated payment is based on a 24.99% interest rate for a 36-month term. "
                    "All loans, including those subject to a personal credit check, are subject to final approval upon "
                    "receipt and review of the completed loan application."
                )
            ),
        ),
        migrations.RunPython(update_financing_copy, migrations.RunPython.noop),
    ]
