# Generated by Codex on 2026-02-22

from django.db import migrations


def update_dealer_tiers(apps, schema_editor):
    DealerTierLevel = apps.get_model("core", "DealerTierLevel")
    updates = {
        "TIER_5": {"label": "T1", "discount_percent": 15},
        "TIER_10": {"label": "T2", "discount_percent": 20},
        "TIER_15": {"label": "T3", "discount_percent": 25},
    }
    for code, payload in updates.items():
        DealerTierLevel.objects.filter(code=code).update(**payload)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0112_financing_autologiq_copy"),
    ]

    operations = [
        migrations.RunPython(update_dealer_tiers, migrations.RunPython.noop),
    ]
