# Generated by Codex on 2026-02-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0113_dealer_tier_renames"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingDayOverride",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("status", models.CharField(choices=[("open", "Open"), ("closed", "Closed")], default="open", max_length=12)),
                ("note", models.CharField(blank=True, max_length=160)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking day override",
                "verbose_name_plural": "Booking day overrides",
                "ordering": ("date",),
            },
        ),
        migrations.AddField(
            model_name="servicespagecopy",
            name="booking_weekend_closed_label",
            field=models.CharField(default="Weekends are closed. Call for availability.", max_length=140),
        ),
    ]

