# Generated by Django 5.2.4 on 2026-02-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0114_booking_day_override_and_weekend_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dealerapplication",
            name="assigned_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "T1"),
                    ("TIER_10", "T2"),
                    ("TIER_15", "T3"),
                ],
                help_text="Tier granted by the admin team when approving the account.",
                max_length=16,
                verbose_name="Assigned tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealerapplication",
            name="preferred_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "T1"),
                    ("TIER_10", "T2"),
                    ("TIER_15", "T3"),
                ],
                default="TIER_5",
                help_text="Requested tier based on projected volume.",
                max_length=16,
                verbose_name="Preferred tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealertierlevel",
            name="code",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "T1"),
                    ("TIER_10", "T2"),
                    ("TIER_15", "T3"),
                ],
                max_length=16,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="leadsubmissionevent",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("site_notice", "Site notice signup"),
                    ("service_lead", "Service lead"),
                    ("fitment_request", "Fitment request"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dealer_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "None"),
                    ("TIER_5", "T1"),
                    ("TIER_10", "T2"),
                    ("TIER_15", "T3"),
                ],
                default="NONE",
                max_length=16,
                verbose_name="Dealer tier",
            ),
        ),
    ]
