# Generated by Django 5.2.4 on 2026-03-01 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0115_alter_dealerapplication_assigned_tier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteContactSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "singleton_id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, unique=True
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="support@badguymotors.com", max_length=254
                    ),
                ),
                (
                    "office_phone",
                    models.CharField(default="+14035250432", max_length=32),
                ),
                (
                    "office_phone_display",
                    models.CharField(default="(403) 525-0432", max_length=40),
                ),
                ("text_phone", models.CharField(default="+15874060101", max_length=32)),
                (
                    "text_phone_display",
                    models.CharField(default="(587) 406-0101", max_length=40),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site contact settings",
                "verbose_name_plural": "Site contact settings",
                "ordering": ("singleton_id",),
            },
        ),
    ]
