# Generated by Django 5.2.4 on 2026-03-10 20:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0117_faqpagecopy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLoginEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logged_in_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("ip_location", models.CharField(blank=True, max_length=255)),
                ("user_agent", models.TextField(blank=True)),
                ("login_path", models.CharField(blank=True, max_length=255)),
                ("session_key", models.CharField(blank=True, max_length=64)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_login_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-logged_in_at",),
                "indexes": [
                    models.Index(
                        fields=["user", "logged_in_at"],
                        name="core_staffl_user_id_ed55f4_idx",
                    ),
                    models.Index(
                        fields=["logged_in_at"], name="core_staffl_logged__47e739_idx"
                    ),
                ],
            },
        ),
    ]
