# Generated by Django 5.2.4 on 2026-03-10 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0118_staffloginevent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leadsubmissionevent",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("site_notice", "Site notice signup"),
                    ("service_lead", "Service lead"),
                    ("fitment_request", "Fitment request"),
                    ("store_review", "Store review"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
