# Generated by Django 5.2.4 on 2026-03-20 05:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0120_adminreleaseseen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminFavoritePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=600)),
                ("label", models.CharField(max_length=160)),
                ("icon", models.CharField(blank=True, max_length=80)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("label", "created_at"),
            },
        ),
        migrations.CreateModel(
            name="AdminRecentPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.CharField(max_length=600)),
                ("label", models.CharField(max_length=160)),
                ("icon", models.CharField(blank=True, max_length=80)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("note", models.CharField(blank=True, max_length=240)),
                ("visit_count", models.PositiveIntegerField(default=1)),
                (
                    "last_visited_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "ordering": ("-last_visited_at",),
            },
        ),
        migrations.RenameIndex(
            model_name="adminreleaseseen",
            new_name="core_adminr_user_id_575f1c_idx",
            old_name="core_adminr_user_id_508eb2_idx",
        ),
        migrations.AddField(
            model_name="adminfavoritepage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_favorite_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adminrecentpage",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="admin_recent_pages",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="adminfavoritepage",
            index=models.Index(
                fields=["user", "label"], name="core_adminf_user_id_9a9b1b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminfavoritepage",
            index=models.Index(
                fields=["user", "created_at"], name="core_adminf_user_id_150f06_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adminfavoritepage",
            unique_together={("user", "url")},
        ),
        migrations.AddIndex(
            model_name="adminrecentpage",
            index=models.Index(
                fields=["user", "last_visited_at"],
                name="core_adminr_user_id_248f64_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="adminrecentpage",
            unique_together={("user", "url")},
        ),
    ]
