# Generated by Django 5.2.4 on 2026-04-01 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0122_ensure_master_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=40)),
                ("email", models.EmailField(max_length=254)),
                (
                    "contact_pref",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("call", "Call"),
                            ("email", "Email"),
                        ],
                        default="call",
                        max_length=16,
                    ),
                ),
                ("truck_year", models.PositiveIntegerField()),
                ("truck_make", models.CharField(max_length=80)),
                ("truck_model", models.CharField(max_length=80)),
                (
                    "mileage",
                    models.CharField(
                        choices=[
                            ("under_150k", "Under 150K km"),
                            ("150_250k", "150-250K km"),
                            ("250_400k", "250-400K km"),
                            ("400k_plus", "400K+ km"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "industry",
                    models.CharField(
                        choices=[
                            ("construction", "Construction"),
                            ("oilfield", "Oilfield"),
                            ("farming", "Farming"),
                            ("personal", "Personal"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                ("frustration", models.TextField()),
                ("work_needed", models.JSONField(blank=True, default=list)),
                (
                    "timeline",
                    models.CharField(
                        choices=[
                            ("asap", "ASAP"),
                            ("1_3_months", "1-3 months"),
                            ("3_6_months", "3-6 months"),
                            ("just_researching", "Just researching"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("flagged", models.BooleanField(db_index=True, default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("estimate_sent", "Estimate sent"),
                            ("closed_won", "Closed won"),
                            ("closed_lost", "Closed lost"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead",
                "verbose_name_plural": "Leads",
                "ordering": ("-created_at",),
            },
        ),
    ]
