# Generated by Django 5.2.4 on 2026-04-09 23:24

from django.db import migrations, models


def seed_default_shop_record(apps, schema_editor):
    ShopSharedDataRecord = apps.get_model("core", "ShopSharedDataRecord")
    ShopSharedDataRecord.objects.get_or_create(
        key="bgm-shop-data-v3",
        defaults={
            "shared": True,
            "payload": {
                "jobs": [],
                "leads": [],
                "designs": [],
            },
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0123_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShopSharedDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=120, unique=True)),
                ("shared", models.BooleanField(db_index=True, default=True)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Shop shared data record",
                "verbose_name_plural": "Shop shared data records",
                "ordering": ("key",),
            },
        ),
        migrations.RunPython(seed_default_shop_record, migrations.RunPython.noop),
    ]
