# Generated by Django 5.2.4 on 2026-04-14 21:10

from decimal import Decimal

from django.db import migrations, models


TIER_MAP = {
    "TIER_5": "TIER_1",
    "TIER_10": "TIER_1",
    "TIER_15": "TIER_2",
    "TIER_1": "TIER_1",
    "TIER_2": "TIER_2",
    "NONE": "NONE",
    "": "",
    None: "",
}


def migrate_dealer_tiers(apps, schema_editor):
    DealerApplication = apps.get_model("core", "DealerApplication")
    DealerTierLevel = apps.get_model("core", "DealerTierLevel")
    UserProfile = apps.get_model("core", "UserProfile")

    DealerTierLevel.objects.update_or_create(
        code="NONE",
        defaults={
            "label": "Standard",
            "discount_percent": 0,
            "minimum_spend": 0,
            "sort_order": 0,
            "is_active": False,
            "description": "Standard catalog pricing.",
        },
    )
    DealerTierLevel.objects.update_or_create(
        code="TIER_1",
        defaults={
            "label": "Tier 1",
            "discount_percent": 0,
            "minimum_spend": 15000,
            "sort_order": 1,
            "is_active": True,
            "description": "Unlocks after CAD 15,000 in lifetime in-house product purchases.",
        },
    )
    DealerTierLevel.objects.update_or_create(
        code="TIER_2",
        defaults={
            "label": "Tier 2",
            "discount_percent": 0,
            "minimum_spend": 50000,
            "sort_order": 2,
            "is_active": True,
            "description": "Unlocks after CAD 50,000 in lifetime in-house product purchases.",
        },
    )
    DealerTierLevel.objects.filter(code__in=["TIER_5", "TIER_10", "TIER_15"]).delete()

    spend_by_user: dict[int, Decimal] = {}
    try:
        OrderItem = apps.get_model("store", "OrderItem")
        eligible_items = (
            OrderItem.objects.exclude(order__status="cancelled")
            .filter(order__user_id__isnull=False)
            .filter(models.Q(order__payment_status="paid") | models.Q(order__status="completed"))
            .values("order__user_id", "qty", "price_at_moment")
        )
        for item in eligible_items.iterator():
            user_id = item.get("order__user_id")
            if not user_id:
                continue
            qty = int(item.get("qty") or 0)
            price = item.get("price_at_moment") or Decimal("0.00")
            try:
                spend_by_user[user_id] = spend_by_user.get(user_id, Decimal("0.00")) + (Decimal(price) * qty)
            except Exception:
                continue
    except LookupError:
        spend_by_user = {}

    for profile in UserProfile.objects.all().iterator():
        if not getattr(profile, "is_dealer", False):
            new_tier = "NONE"
        else:
            spent = spend_by_user.get(profile.user_id, Decimal("0.00"))
            if spent >= Decimal("50000.00"):
                new_tier = "TIER_2"
            elif spent >= Decimal("15000.00"):
                new_tier = "TIER_1"
            else:
                legacy_tier = TIER_MAP.get(profile.dealer_tier, "NONE")
                new_tier = legacy_tier or "NONE"
        if profile.dealer_tier != new_tier:
            profile.dealer_tier = new_tier
            profile.save(update_fields=["dealer_tier"])

    for application in DealerApplication.objects.all().iterator():
        preferred_tier = TIER_MAP.get(application.preferred_tier, "")
        assigned_tier = TIER_MAP.get(application.assigned_tier, "")
        if preferred_tier == "":
            preferred_tier = "TIER_1"
        fields = []
        if application.preferred_tier != preferred_tier:
            application.preferred_tier = preferred_tier
            fields.append("preferred_tier")
        if application.assigned_tier != assigned_tier:
            application.assigned_tier = assigned_tier
            fields.append("assigned_tier")
        if fields:
            application.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0127_shoprateline"),
        ("store", "0037_product_show_liner_pricing_guide"),
    ]

    operations = [
        migrations.RunPython(migrate_dealer_tiers, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="dealertierlevel",
            name="discount_percent",
        ),
        migrations.AlterField(
            model_name="dealerapplication",
            name="assigned_tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("NONE", "Standard"),
                    ("TIER_1", "Tier 1"),
                    ("TIER_2", "Tier 2"),
                ],
                help_text="Tier granted by the admin team when approving the account.",
                max_length=16,
                verbose_name="Assigned tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealerapplication",
            name="preferred_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "Standard"),
                    ("TIER_1", "Tier 1"),
                    ("TIER_2", "Tier 2"),
                ],
                default="TIER_1",
                help_text="Requested tier based on projected volume.",
                max_length=16,
                verbose_name="Preferred tier",
            ),
        ),
        migrations.AlterField(
            model_name="dealertierlevel",
            name="code",
            field=models.CharField(
                choices=[
                    ("NONE", "Standard"),
                    ("TIER_1", "Tier 1"),
                    ("TIER_2", "Tier 2"),
                ],
                max_length=16,
                unique=True,
                verbose_name="Code",
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="dealer_tier",
            field=models.CharField(
                choices=[
                    ("NONE", "Standard"),
                    ("TIER_1", "Tier 1"),
                    ("TIER_2", "Tier 2"),
                ],
                default="NONE",
                max_length=16,
                verbose_name="Dealer tier",
            ),
        ),
    ]
