# Generated by Django 5.2.6 on 2025-11-15 07:54

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TelegramBotSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="Operations bot", max_length=120)),
                (
                    "bot_token",
                    models.CharField(
                        blank=True,
                        help_text="Bot token issued by BotFather.",
                        max_length=255,
                    ),
                ),
                (
                    "enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Disable to temporarily stop sending Telegram notifications.",
                    ),
                ),
                (
                    "admin_chat_ids",
                    models.TextField(
                        help_text="Comma or space separated chat IDs that should receive automated alerts."
                    ),
                ),
                (
                    "allowed_user_ids",
                    models.TextField(
                        blank=True,
                        help_text="Optional Telegram user IDs allowed to interact with the bot commands. Fallbacks to admin chats when empty.",
                    ),
                ),
                ("notify_on_new_appointment", models.BooleanField(default=True)),
                ("notify_on_new_order", models.BooleanField(default=True)),
                (
                    "digest_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Enable to send a consolidated daily summary through the bot.",
                    ),
                ),
                (
                    "digest_hour_local",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="Hour (0-23) at which the digest command should run (local server time).",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(23),
                        ],
                    ),
                ),
                ("last_digest_sent_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram bot settings",
                "verbose_name_plural": "Telegram bot settings",
            },
        ),
        migrations.CreateModel(
            name="TelegramMessageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(db_index=True, max_length=64)),
                ("chat_id", models.BigIntegerField()),
                ("payload", models.TextField()),
                ("success", models.BooleanField(default=True)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Telegram message log",
                "verbose_name_plural": "Telegram message log",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TelegramReminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("message", models.TextField()),
                (
                    "scheduled_for",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "target_chat_ids",
                    models.TextField(
                        blank=True,
                        help_text="Optional override for chat IDs. Uses admin recipients when empty.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram reminder",
                "verbose_name_plural": "Telegram reminders",
                "ordering": ["-scheduled_for"],
            },
        ),
    ]
