# Generated by Django 5.2.6 on 2025-11-15 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("chat_id", models.BigIntegerField(unique=True)),
                ("notes", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Telegram contact",
                "verbose_name_plural": "Telegram contacts",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="telegramreminder",
            name="contacts",
            field=models.ManyToManyField(
                blank=True,
                help_text="Select saved contacts to receive this reminder.",
                related_name="reminders",
                to="notifications.telegramcontact",
            ),
        ),
    ]
