# Generated by Django 5.2.6 on 2025-11-30 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_telegramcontact_telegramreminder_contacts"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramRecipientSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("chat_id", models.BigIntegerField(unique=True)),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="Optional hint about who owns this chat ID.",
                        max_length=120,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipient_slots",
                        to="notifications.telegrambotsettings",
                    ),
                ),
            ],
            options={
                "verbose_name": "Telegram recipient slot",
                "verbose_name_plural": "Telegram recipient slots",
                "ordering": ["chat_id"],
            },
        ),
    ]
