# Generated by Django 5.2.6 on 2025-11-30 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_telegramrecipientslot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="telegrambotsettings",
            name="admin_chat_ids",
            field=models.TextField(
                blank=True,
                help_text="Comma or space separated chat IDs that should receive automated alerts.",
            ),
        ),
    ]
